-- ============================================================
-- COMMIT 1: Product Management 2.0 — Database Foundation
-- ============================================================
-- Rules:
--   * NEVER DROP existing columns on public.products
--   * NEVER ALTER existing column types
--   * All new columns are nullable or have defaults → zero downtime
--   * All new tables use IF NOT EXISTS
--   * All policies use existence checks
-- ============================================================

-- ------------------------------------------------------------
-- HELPER: ensure set_updated_at function exists (idempotent)
-- ------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ============================================================
-- 1. CATEGORIES (normalized; replaces free-text category column)
-- ============================================================
create table if not exists public.categories (
  id          bigint generated by default as identity primary key,
  name        text   not null,
  slug        text   not null unique,
  description text,
  display_order integer not null default 0,
  active      boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

drop trigger if exists categories_set_updated_at on public.categories;
create trigger categories_set_updated_at
  before update on public.categories
  for each row execute function public.set_updated_at();

create index if not exists categories_slug_idx   on public.categories (slug);
create index if not exists categories_active_idx on public.categories (active);

alter table public.categories enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='categories' and policyname='categories_public_read') then
    create policy categories_public_read on public.categories for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='categories' and policyname='categories_service_write') then
    create policy categories_service_write on public.categories for all to service_role using (true) with check (true);
  end if;
end $$;

-- ============================================================
-- 2. SUBCATEGORIES
-- ============================================================
create table if not exists public.subcategories (
  id          bigint generated by default as identity primary key,
  category_id bigint not null references public.categories (id) on delete cascade,
  name        text   not null,
  slug        text   not null unique,
  description text,
  display_order integer not null default 0,
  active      boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

drop trigger if exists subcategories_set_updated_at on public.subcategories;
create trigger subcategories_set_updated_at
  before update on public.subcategories
  for each row execute function public.set_updated_at();

create index if not exists subcategories_category_id_idx on public.subcategories (category_id);
create index if not exists subcategories_slug_idx        on public.subcategories (slug);

alter table public.subcategories enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='subcategories' and policyname='subcategories_public_read') then
    create policy subcategories_public_read on public.subcategories for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='subcategories' and policyname='subcategories_service_write') then
    create policy subcategories_service_write on public.subcategories for all to service_role using (true) with check (true);
  end if;
end $$;

-- ============================================================
-- 3. COLLECTIONS
-- ============================================================
create table if not exists public.collections (
  id          bigint generated by default as identity primary key,
  name        text   not null,
  slug        text   not null unique,
  description text,
  banner_url  text,
  display_order integer not null default 0,
  active      boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

drop trigger if exists collections_set_updated_at on public.collections;
create trigger collections_set_updated_at
  before update on public.collections
  for each row execute function public.set_updated_at();

create index if not exists collections_slug_idx   on public.collections (slug);
create index if not exists collections_active_idx on public.collections (active);

alter table public.collections enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='collections' and policyname='collections_public_read') then
    create policy collections_public_read on public.collections for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='collections' and policyname='collections_service_write') then
    create policy collections_service_write on public.collections for all to service_role using (true) with check (true);
  end if;
end $$;

-- ============================================================
-- 4. TAGS
-- ============================================================
create table if not exists public.tags (
  id   bigint generated by default as identity primary key,
  name text   not null unique,
  slug text   not null unique
);

create index if not exists tags_slug_idx on public.tags (slug);

alter table public.tags enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='tags' and policyname='tags_public_read') then
    create policy tags_public_read on public.tags for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='tags' and policyname='tags_service_write') then
    create policy tags_service_write on public.tags for all to service_role using (true) with check (true);
  end if;
end $$;

-- ============================================================
-- 5. ATTRIBUTE MASTER TABLES
-- ============================================================
-- Generic pattern: id, name, slug, display_order, active
-- One table per attribute type to allow independent management.

create table if not exists public.attr_fabric (
  id   bigint generated by default as identity primary key,
  name text   not null unique,
  slug text   not null unique,
  display_order integer not null default 0,
  active boolean not null default true
);
alter table public.attr_fabric enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='attr_fabric' and policyname='attr_fabric_public_read') then
    create policy attr_fabric_public_read on public.attr_fabric for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='attr_fabric' and policyname='attr_fabric_service_write') then
    create policy attr_fabric_service_write on public.attr_fabric for all to service_role using (true) with check (true);
  end if;
end $$;

create table if not exists public.attr_color (
  id   bigint generated by default as identity primary key,
  name text   not null unique,
  slug text   not null unique,
  hex  text,
  display_order integer not null default 0,
  active boolean not null default true
);
alter table public.attr_color enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='attr_color' and policyname='attr_color_public_read') then
    create policy attr_color_public_read on public.attr_color for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='attr_color' and policyname='attr_color_service_write') then
    create policy attr_color_service_write on public.attr_color for all to service_role using (true) with check (true);
  end if;
end $$;

create table if not exists public.attr_occasion (
  id   bigint generated by default as identity primary key,
  name text   not null unique,
  slug text   not null unique,
  display_order integer not null default 0,
  active boolean not null default true
);
alter table public.attr_occasion enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='attr_occasion' and policyname='attr_occasion_public_read') then
    create policy attr_occasion_public_read on public.attr_occasion for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='attr_occasion' and policyname='attr_occasion_service_write') then
    create policy attr_occasion_service_write on public.attr_occasion for all to service_role using (true) with check (true);
  end if;
end $$;

create table if not exists public.attr_pattern (
  id   bigint generated by default as identity primary key,
  name text   not null unique,
  slug text   not null unique,
  display_order integer not null default 0,
  active boolean not null default true
);
alter table public.attr_pattern enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='attr_pattern' and policyname='attr_pattern_public_read') then
    create policy attr_pattern_public_read on public.attr_pattern for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='attr_pattern' and policyname='attr_pattern_service_write') then
    create policy attr_pattern_service_write on public.attr_pattern for all to service_role using (true) with check (true);
  end if;
end $$;

create table if not exists public.attr_fit (
  id   bigint generated by default as identity primary key,
  name text   not null unique,
  slug text   not null unique,
  display_order integer not null default 0,
  active boolean not null default true
);
alter table public.attr_fit enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='attr_fit' and policyname='attr_fit_public_read') then
    create policy attr_fit_public_read on public.attr_fit for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='attr_fit' and policyname='attr_fit_service_write') then
    create policy attr_fit_service_write on public.attr_fit for all to service_role using (true) with check (true);
  end if;
end $$;

create table if not exists public.attr_sleeve (
  id   bigint generated by default as identity primary key,
  name text   not null unique,
  slug text   not null unique,
  display_order integer not null default 0,
  active boolean not null default true
);
alter table public.attr_sleeve enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='attr_sleeve' and policyname='attr_sleeve_public_read') then
    create policy attr_sleeve_public_read on public.attr_sleeve for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='attr_sleeve' and policyname='attr_sleeve_service_write') then
    create policy attr_sleeve_service_write on public.attr_sleeve for all to service_role using (true) with check (true);
  end if;
end $$;

create table if not exists public.attr_neck (
  id   bigint generated by default as identity primary key,
  name text   not null unique,
  slug text   not null unique,
  display_order integer not null default 0,
  active boolean not null default true
);
alter table public.attr_neck enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='attr_neck' and policyname='attr_neck_public_read') then
    create policy attr_neck_public_read on public.attr_neck for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='attr_neck' and policyname='attr_neck_service_write') then
    create policy attr_neck_service_write on public.attr_neck for all to service_role using (true) with check (true);
  end if;
end $$;

create table if not exists public.attr_work (
  id   bigint generated by default as identity primary key,
  name text   not null unique,
  slug text   not null unique,
  display_order integer not null default 0,
  active boolean not null default true
);
alter table public.attr_work enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='attr_work' and policyname='attr_work_public_read') then
    create policy attr_work_public_read on public.attr_work for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='attr_work' and policyname='attr_work_service_write') then
    create policy attr_work_service_write on public.attr_work for all to service_role using (true) with check (true);
  end if;
end $$;

create table if not exists public.attr_length (
  id   bigint generated by default as identity primary key,
  name text   not null unique,
  slug text   not null unique,
  display_order integer not null default 0,
  active boolean not null default true
);
alter table public.attr_length enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='attr_length' and policyname='attr_length_public_read') then
    create policy attr_length_public_read on public.attr_length for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='attr_length' and policyname='attr_length_service_write') then
    create policy attr_length_service_write on public.attr_length for all to service_role using (true) with check (true);
  end if;
end $$;

-- ============================================================
-- 6. SIZE MASTER + SIZE CHARTS
-- ============================================================
create table if not exists public.size_master (
  id            bigint generated by default as identity primary key,
  name          text   not null unique,   -- e.g. XS, S, M, L, XL, XXL, 3XL, 4XL
  sort_order    integer not null default 0,
  active        boolean not null default true
);
alter table public.size_master enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='size_master' and policyname='size_master_public_read') then
    create policy size_master_public_read on public.size_master for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='size_master' and policyname='size_master_service_write') then
    create policy size_master_service_write on public.size_master for all to service_role using (true) with check (true);
  end if;
end $$;

-- Seed standard sizes (idempotent)
insert into public.size_master (name, sort_order) values
  ('XS',  10),
  ('S',   20),
  ('M',   30),
  ('L',   40),
  ('XL',  50),
  ('XXL', 60),
  ('3XL', 70),
  ('4XL', 80)
on conflict (name) do nothing;

create table if not exists public.size_charts (
  id          bigint generated by default as identity primary key,
  name        text   not null unique,    -- e.g. "Women Kurtis", "Men Shirts"
  description text,
  chart_data  jsonb  not null default '[]'::jsonb,  -- [{size, bust, waist, hip, ...}]
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

drop trigger if exists size_charts_set_updated_at on public.size_charts;
create trigger size_charts_set_updated_at
  before update on public.size_charts
  for each row execute function public.set_updated_at();

alter table public.size_charts enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='size_charts' and policyname='size_charts_public_read') then
    create policy size_charts_public_read on public.size_charts for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='size_charts' and policyname='size_charts_service_write') then
    create policy size_charts_service_write on public.size_charts for all to service_role using (true) with check (true);
  end if;
end $$;

-- ============================================================
-- 7. EXTEND public.products (additive only — zero breakage)
-- ============================================================
-- All new columns are nullable or have safe defaults.
-- Existing queries continue to work unchanged.

alter table public.products
  -- Normalized FKs (nullable so existing rows are unaffected)
  add column if not exists category_id      bigint references public.categories    (id) on delete set null,
  add column if not exists subcategory_id   bigint references public.subcategories (id) on delete set null,
  add column if not exists collection_id    bigint references public.collections   (id) on delete set null,
  add column if not exists size_chart_id    bigint references public.size_charts   (id) on delete set null,

  -- Attribute FKs (normalized; nullable)
  add column if not exists attr_fabric_id   bigint references public.attr_fabric   (id) on delete set null,
  add column if not exists attr_color_id    bigint references public.attr_color    (id) on delete set null,
  add column if not exists attr_occasion_id bigint references public.attr_occasion (id) on delete set null,
  add column if not exists attr_pattern_id  bigint references public.attr_pattern  (id) on delete set null,
  add column if not exists attr_fit_id      bigint references public.attr_fit      (id) on delete set null,
  add column if not exists attr_sleeve_id   bigint references public.attr_sleeve   (id) on delete set null,
  add column if not exists attr_neck_id     bigint references public.attr_neck     (id) on delete set null,
  add column if not exists attr_work_id     bigint references public.attr_work     (id) on delete set null,
  add column if not exists attr_length_id   bigint references public.attr_length   (id) on delete set null,

  -- Product master fields
  add column if not exists short_description text,
  add column if not exists brand_name        text,   -- richer brand vs existing brand text column
  add column if not exists display_order     integer not null default 0,

  -- SEO
  add column if not exists seo_keywords  text,
  add column if not exists canonical_url text,

  -- Compliance / Apparel
  add column if not exists hsn_code            text,
  add column if not exists country_of_origin   text not null default 'India',
  add column if not exists manufacturer        text,
  add column if not exists care_instructions   text,
  add column if not exists pattern_text        text,   -- free-text fallback
  add column if not exists occasion_text       text,   -- free-text fallback
  add column if not exists work_type           text,
  add column if not exists fit                 text,
  add column if not exists sleeve              text,
  add column if not exists neck                text,
  add column if not exists length_type         text,
  add column if not exists transparency        text,
  add column if not exists package_contents    text,

  -- Storefront flags
  add column if not exists published_at  timestamptz,
  add column if not exists published_by  uuid references auth.users (id) on delete set null,

  -- Audit
  add column if not exists created_by    uuid references auth.users (id) on delete set null,
  add column if not exists updated_by    uuid references auth.users (id) on delete set null;

-- Indexes for new FK columns
create index if not exists products_category_id_idx      on public.products (category_id);
create index if not exists products_subcategory_id_idx   on public.products (subcategory_id);
create index if not exists products_collection_id_idx    on public.products (collection_id);
create index if not exists products_attr_fabric_id_idx   on public.products (attr_fabric_id);
create index if not exists products_attr_color_id_idx    on public.products (attr_color_id);
create index if not exists products_featured_idx         on public.products (featured);
create index if not exists products_new_arrival_idx      on public.products (new_arrival);
create index if not exists products_best_seller_idx      on public.products (best_seller);
create index if not exists products_display_order_idx    on public.products (display_order);

-- ============================================================
-- 8. PRODUCT IMAGES TABLE
-- ============================================================
create type if not exists public.product_image_type as enum ('primary', 'gallery', 'zoom');

create table if not exists public.product_images (
  id          bigint generated by default as identity primary key,
  product_id  bigint not null references public.products (id) on delete cascade,
  image_type  public.product_image_type not null default 'gallery',
  url         text   not null,
  alt         text,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now()
);

create index if not exists product_images_product_id_idx  on public.product_images (product_id);
create index if not exists product_images_type_idx        on public.product_images (product_id, image_type);
create index if not exists product_images_sort_order_idx  on public.product_images (product_id, sort_order);

alter table public.product_images enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='product_images' and policyname='product_images_public_read') then
    create policy product_images_public_read on public.product_images for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='product_images' and policyname='product_images_service_write') then
    create policy product_images_service_write on public.product_images for all to service_role using (true) with check (true);
  end if;
end $$;

-- ============================================================
-- 9. PRODUCT VARIANTS
-- ============================================================
create type if not exists public.variant_status as enum ('active', 'inactive', 'out_of_stock');

create table if not exists public.product_variants (
  id             bigint generated by default as identity primary key,
  product_id     bigint not null references public.products (id) on delete cascade,
  size_id        bigint references public.size_master (id) on delete set null,
  size_label     text,                              -- free-text override (e.g. "38", "Custom")
  sku            text   not null unique,
  barcode        text,
  mrp            numeric(12,2) not null default 0 check (mrp >= 0),
  selling_price  numeric(12,2) not null default 0 check (selling_price >= 0),
  cost           numeric(12,2)          check (cost >= 0),
  stock          integer not null default 0 check (stock >= 0),
  reserved_stock integer not null default 0 check (reserved_stock >= 0),
  weight_grams   integer          check (weight_grams >= 0),
  length_cm      numeric(8,2)     check (length_cm >= 0),
  width_cm       numeric(8,2)     check (width_cm >= 0),
  height_cm      numeric(8,2)     check (height_cm >= 0),
  status         public.variant_status not null default 'active',
  is_default     boolean not null default false,
  sort_order     integer not null default 0,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  constraint selling_lte_mrp check (selling_price <= mrp)
);

drop trigger if exists product_variants_set_updated_at on public.product_variants;
create trigger product_variants_set_updated_at
  before update on public.product_variants
  for each row execute function public.set_updated_at();

create index if not exists product_variants_product_id_idx on public.product_variants (product_id);
create index if not exists product_variants_sku_idx        on public.product_variants (sku);
create index if not exists product_variants_status_idx     on public.product_variants (product_id, status);
create index if not exists product_variants_default_idx    on public.product_variants (product_id, is_default);

alter table public.product_variants enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='product_variants' and policyname='product_variants_public_read') then
    create policy product_variants_public_read on public.product_variants for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='product_variants' and policyname='product_variants_service_write') then
    create policy product_variants_service_write on public.product_variants for all to service_role using (true) with check (true);
  end if;
end $$;

-- ============================================================
-- 10. PRODUCT TAGS (join table)
-- ============================================================
create table if not exists public.product_tags (
  product_id bigint not null references public.products (id) on delete cascade,
  tag_id     bigint not null references public.tags     (id) on delete cascade,
  primary key (product_id, tag_id)
);

create index if not exists product_tags_product_id_idx on public.product_tags (product_id);
create index if not exists product_tags_tag_id_idx     on public.product_tags (tag_id);

alter table public.product_tags enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='product_tags' and policyname='product_tags_public_read') then
    create policy product_tags_public_read on public.product_tags for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='product_tags' and policyname='product_tags_service_write') then
    create policy product_tags_service_write on public.product_tags for all to service_role using (true) with check (true);
  end if;
end $$;

-- ============================================================
-- 11. PRODUCT AUDIT LOG
-- ============================================================
create table if not exists public.product_audit_log (
  id          bigint generated by default as identity primary key,
  product_id  bigint references public.products (id) on delete set null,
  actor_id    uuid   references auth.users (id) on delete set null,
  event       text   not null,   -- created, updated, published, deactivated, deleted
  diff        jsonb,             -- {before: {}, after: {}} snapshot
  metadata    jsonb,
  created_at  timestamptz not null default now()
);

create index if not exists product_audit_log_product_id_idx on public.product_audit_log (product_id);
create index if not exists product_audit_log_created_at_idx on public.product_audit_log (created_at desc);
create index if not exists product_audit_log_actor_id_idx   on public.product_audit_log (actor_id);

alter table public.product_audit_log enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='product_audit_log' and policyname='product_audit_log_service_write') then
    create policy product_audit_log_service_write on public.product_audit_log for all to service_role using (true) with check (true);
  end if;
  -- Admins (authenticated) can read audit log; anon cannot
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='product_audit_log' and policyname='product_audit_log_auth_read') then
    create policy product_audit_log_auth_read on public.product_audit_log for select to authenticated using (true);
  end if;
end $$;

-- ============================================================
-- DONE
-- ============================================================
-- No UI, no API, no service changes.
-- The existing products table is fully backward-compatible.
-- ============================================================
