-- ============================================================
-- 20260803020000_products_v2_complete_columns.sql
--
-- PURPOSE
-- -------
-- Product V2 service references every column listed below in:
--   PRODUCT_V2_SELECT (read path)
--   insertRow         (create path)
--   updateRow fieldMap (update path)
--
-- These columns were declared in 20260718100000 /
-- 20260727000000 but may be absent on the live database
-- depending on the migration push state.
--
-- SAFETY
-- ------
-- Every ADD COLUMN uses IF NOT EXISTS.
-- Every CREATE INDEX uses IF NOT EXISTS.
-- No DROP, no ALTER TYPE, no data loss.
-- FK references use IF NOT EXISTS column guards.
-- Idempotent: safe to run on any state of the products table.
-- ============================================================

-- ============================================================
-- PREREQUISITE: ensure all FK target tables exist
-- (created by 20260727000000 / 20260718100000 — these are
--  no-ops if those migrations already ran)
-- ============================================================

create table if not exists public.categories (
  id            bigint generated by default as identity primary key,
  name          text    not null,
  slug          text    not null unique,
  description   text,
  display_order integer not null default 0,
  active        boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table if not exists public.subcategories (
  id            bigint generated by default as identity primary key,
  category_id   bigint  not null references public.categories (id) on delete cascade,
  name          text    not null,
  slug          text    not null unique,
  description   text,
  display_order integer not null default 0,
  active        boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table if not exists public.collections (
  id            bigint generated by default as identity primary key,
  name          text    not null,
  slug          text    not null unique,
  description   text,
  banner_url    text,
  display_order integer not null default 0,
  active        boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table if not exists public.size_charts (
  id          bigint generated by default as identity primary key,
  name        text    not null unique,
  description text,
  chart_data  jsonb   not null default '[]'::jsonb,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.attr_fabric   (id bigint generated by default as identity primary key, name text not null unique, slug text not null unique, display_order integer not null default 0, active boolean not null default true);
create table if not exists public.attr_color    (id bigint generated by default as identity primary key, name text not null unique, slug text not null unique, hex text, display_order integer not null default 0, active boolean not null default true);
create table if not exists public.attr_occasion (id bigint generated by default as identity primary key, name text not null unique, slug text not null unique, display_order integer not null default 0, active boolean not null default true);
create table if not exists public.attr_pattern  (id bigint generated by default as identity primary key, name text not null unique, slug text not null unique, display_order integer not null default 0, active boolean not null default true);
create table if not exists public.attr_fit      (id bigint generated by default as identity primary key, name text not null unique, slug text not null unique, display_order integer not null default 0, active boolean not null default true);
create table if not exists public.attr_sleeve   (id bigint generated by default as identity primary key, name text not null unique, slug text not null unique, display_order integer not null default 0, active boolean not null default true);
create table if not exists public.attr_neck     (id bigint generated by default as identity primary key, name text not null unique, slug text not null unique, display_order integer not null default 0, active boolean not null default true);
create table if not exists public.attr_work     (id bigint generated by default as identity primary key, name text not null unique, slug text not null unique, display_order integer not null default 0, active boolean not null default true);
create table if not exists public.attr_length   (id bigint generated by default as identity primary key, name text not null unique, slug text not null unique, display_order integer not null default 0, active boolean not null default true);

-- ============================================================
-- EXTEND public.products
-- Every statement is ADD COLUMN IF NOT EXISTS → pure no-op
-- when the column already exists.
-- ============================================================

-- ── FK columns (normalized catalog references) ───────────────
alter table public.products
  add column if not exists category_id      bigint references public.categories    (id) on delete set null,
  add column if not exists subcategory_id   bigint references public.subcategories (id) on delete set null,
  add column if not exists collection_id    bigint references public.collections   (id) on delete set null,
  add column if not exists size_chart_id    bigint references public.size_charts   (id) on delete set null;

-- ── Attribute FK columns ─────────────────────────────────────
alter table public.products
  add column if not exists attr_fabric_id   bigint references public.attr_fabric   (id) on delete set null,
  add column if not exists attr_color_id    bigint references public.attr_color    (id) on delete set null,
  add column if not exists attr_occasion_id bigint references public.attr_occasion (id) on delete set null,
  add column if not exists attr_pattern_id  bigint references public.attr_pattern  (id) on delete set null,
  add column if not exists attr_fit_id      bigint references public.attr_fit      (id) on delete set null,
  add column if not exists attr_sleeve_id   bigint references public.attr_sleeve   (id) on delete set null,
  add column if not exists attr_neck_id     bigint references public.attr_neck     (id) on delete set null,
  add column if not exists attr_work_id     bigint references public.attr_work     (id) on delete set null,
  add column if not exists attr_length_id   bigint references public.attr_length   (id) on delete set null;

-- ── Product content fields ────────────────────────────────────
alter table public.products
  add column if not exists short_description text,
  add column if not exists brand_name        text,   -- added by 20260803010000; IF NOT EXISTS = no-op
  add column if not exists display_order     integer not null default 0;

-- ── SEO fields ───────────────────────────────────────────────
alter table public.products
  add column if not exists seo_keywords  text,
  add column if not exists canonical_url text;

-- ── Compliance + apparel detail fields ───────────────────────
alter table public.products
  add column if not exists hsn_code           text,
  add column if not exists country_of_origin  text not null default 'India',
  add column if not exists manufacturer       text,
  add column if not exists care_instructions  text,
  add column if not exists pattern_text       text,
  add column if not exists occasion_text      text,
  add column if not exists work_type          text,
  add column if not exists fit                text,
  add column if not exists sleeve             text,
  add column if not exists neck               text,
  add column if not exists length_type        text,
  add column if not exists transparency       text,
  add column if not exists package_contents   text;

-- ── Publish workflow fields ───────────────────────────────────
alter table public.products
  add column if not exists published_at timestamptz,
  add column if not exists published_by uuid references auth.users (id) on delete set null;

-- ── Audit trail fields ───────────────────────────────────────
alter table public.products
  add column if not exists created_by uuid references auth.users (id) on delete set null,
  add column if not exists updated_by uuid references auth.users (id) on delete set null;

-- ============================================================
-- BACKFILL
-- ============================================================

-- brand_name: copy from existing brand column for all rows
-- where brand_name is still null (no-op if 20260803010000
-- already ran this backfill)
update public.products
set    brand_name = brand
where  brand_name is null
  and  brand is not null;

-- hsn_code: copy from existing hsn column (legacy free-text)
update public.products
set    hsn_code = hsn
where  hsn_code is null
  and  hsn is not null;

-- ============================================================
-- INDEXES
-- All use IF NOT EXISTS — no-ops if already present
-- ============================================================

create index if not exists products_category_id_idx      on public.products (category_id);
create index if not exists products_subcategory_id_idx   on public.products (subcategory_id);
create index if not exists products_collection_id_idx    on public.products (collection_id);
create index if not exists products_attr_fabric_id_idx   on public.products (attr_fabric_id);
create index if not exists products_attr_color_id_idx    on public.products (attr_color_id);
create index if not exists products_featured_idx         on public.products (featured);
create index if not exists products_new_arrival_idx      on public.products (new_arrival);
create index if not exists products_best_seller_idx      on public.products (best_seller);
create index if not exists products_display_order_idx    on public.products (display_order);
create index if not exists products_published_at_idx     on public.products (published_at);
create index if not exists products_canonical_url_idx    on public.products (canonical_url);
create index if not exists products_brand_name_idx       on public.products (brand_name);

-- ============================================================
-- RELOAD POSTGREST SCHEMA CACHE
-- ============================================================
select pg_notify('pgrst', 'reload schema');
