-- ============================================================
-- INVENTORY VENDOR DOMAIN
-- 20260803000000_inventory_vendor_domain.sql  (repaired)
--
-- Creates / patches all tables, views, and RPC functions
-- required by InventoryService (src/services/inventory.service.ts)
-- and the /inventory/purchase-orders Next.js routes.
--
-- Safety guarantees:
--   * CREATE TABLE           → IF NOT EXISTS
--   * ALTER TABLE ADD COLUMN → IF NOT EXISTS  (on every column)
--   * CREATE INDEX           → inside DO $$ column-existence guard
--   * CREATE TYPE / enum     → DO $$ EXCEPTION WHEN duplicate_object
--   * CREATE POLICY          → pg_policies existence check
--   * CREATE OR REPLACE      → functions and views
--   * No DROP TABLE / DROP COLUMN
--   * No data mutations
--   * Fully idempotent — safe to run on a fresh DB or over partial state
-- ============================================================

-- ============================================================
-- SECTION 1 — ENUMS
-- ============================================================

do $$ begin
  create type public.po_status as enum
    ('draft', 'sent', 'partial', 'received', 'cancelled');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.transfer_status as enum
    ('pending', 'in_transit', 'completed', 'cancelled');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.stock_status as enum
    ('in_stock', 'low_stock', 'out_of_stock');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.adjustment_reason as enum (
    'cycle_count', 'damage_write_off', 'damage_recovery',
    'theft_loss', 'expiry', 'found_surplus',
    'vendor_credit', 'sample_used', 'other'
  );
exception when duplicate_object then null; end $$;

-- ============================================================
-- SECTION 2 — WAREHOUSES
-- ============================================================

create table if not exists public.warehouses (
  id         bigint generated by default as identity primary key,
  name       text    not null,
  code       text    not null,
  address    text,
  is_default boolean not null default false,
  is_active  boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Ensure unique constraints exist (safe if already present)
do $$ begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.warehouses'::regclass
      and conname  = 'warehouses_name_key'
  ) then
    alter table public.warehouses add constraint warehouses_name_key unique (name);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.warehouses'::regclass
      and conname  = 'warehouses_code_key'
  ) then
    alter table public.warehouses add constraint warehouses_code_key unique (code);
  end if;
end $$;

-- Ensure all columns exist
alter table public.warehouses
  add column if not exists address    text,
  add column if not exists is_default boolean not null default false,
  add column if not exists is_active  boolean not null default true,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

drop trigger if exists warehouses_set_updated_at on public.warehouses;
create trigger warehouses_set_updated_at
  before update on public.warehouses
  for each row execute function public.set_updated_at();

do $$ begin
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='warehouses' and indexname='warehouses_is_active_idx') then
    create index warehouses_is_active_idx  on public.warehouses (is_active);
  end if;
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='warehouses' and indexname='warehouses_is_default_idx') then
    create index warehouses_is_default_idx on public.warehouses (is_default);
  end if;
end $$;

alter table public.warehouses enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='warehouses' and policyname='warehouses_service_all') then
    create policy warehouses_service_all on public.warehouses for all to service_role using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='warehouses' and policyname='warehouses_auth_read') then
    create policy warehouses_auth_read on public.warehouses for select to authenticated using (true);
  end if;
end $$;

-- ============================================================
-- SECTION 3 — VENDORS
-- ============================================================

create table if not exists public.vendors (
  id            bigint generated by default as identity primary key,
  name          text    not null,
  code          text    not null,
  gstin         text,
  email         text,
  phone         text,
  address       text,
  payment_terms integer not null default 30 check (payment_terms >= 0),
  is_active     boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

do $$ begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.vendors'::regclass and conname = 'vendors_code_key'
  ) then
    alter table public.vendors add constraint vendors_code_key unique (code);
  end if;
end $$;

alter table public.vendors
  add column if not exists gstin         text,
  add column if not exists email         text,
  add column if not exists phone         text,
  add column if not exists address       text,
  add column if not exists payment_terms integer not null default 30,
  add column if not exists is_active     boolean not null default true,
  add column if not exists created_at    timestamptz not null default now(),
  add column if not exists updated_at    timestamptz not null default now();

drop trigger if exists vendors_set_updated_at on public.vendors;
create trigger vendors_set_updated_at
  before update on public.vendors
  for each row execute function public.set_updated_at();

do $$ begin
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='vendors' and indexname='vendors_is_active_idx') then
    create index vendors_is_active_idx on public.vendors (is_active);
  end if;
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='vendors' and indexname='vendors_name_idx') then
    create index vendors_name_idx on public.vendors (name);
  end if;
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='vendors' and indexname='vendors_code_idx') then
    create index vendors_code_idx on public.vendors (code);
  end if;
end $$;

alter table public.vendors enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='vendors' and policyname='vendors_service_all') then
    create policy vendors_service_all on public.vendors for all to service_role using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='vendors' and policyname='vendors_auth_read') then
    create policy vendors_auth_read on public.vendors for select to authenticated using (true);
  end if;
end $$;

-- ============================================================
-- SECTION 4 — INVENTORY (stock ledger)
-- ============================================================

create table if not exists public.inventory (
  id                  bigint generated by default as identity primary key,
  warehouse_id        bigint  not null,
  product_id          bigint  not null,
  variant_id          bigint,
  product_name        text    not null default '',
  product_sku         text    not null default '',
  variant_sku         text,
  size_label          text,
  available_qty       integer not null default 0,
  reserved_qty        integer not null default 0,
  damaged_qty         integer not null default 0,
  avg_cost_price      numeric(12,4) not null default 0,
  low_stock_threshold integer not null default 10,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- Ensure all columns exist on pre-existing table
alter table public.inventory
  add column if not exists warehouse_id        bigint,
  add column if not exists product_id          bigint,
  add column if not exists variant_id          bigint,
  add column if not exists product_name        text    not null default '',
  add column if not exists product_sku         text    not null default '',
  add column if not exists variant_sku         text,
  add column if not exists size_label          text,
  add column if not exists available_qty       integer not null default 0,
  add column if not exists reserved_qty        integer not null default 0,
  add column if not exists damaged_qty         integer not null default 0,
  add column if not exists avg_cost_price      numeric(12,4) not null default 0,
  add column if not exists low_stock_threshold integer not null default 10,
  add column if not exists created_at          timestamptz not null default now(),
  add column if not exists updated_at          timestamptz not null default now();

-- FK constraints — add only if columns exist and FK absent
do $$ begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.inventory'::regclass and conname = 'inventory_warehouse_id_fkey'
  ) then
    alter table public.inventory
      add constraint inventory_warehouse_id_fkey
      foreign key (warehouse_id) references public.warehouses (id) on delete restrict;
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.inventory'::regclass and conname = 'inventory_product_id_fkey'
  ) then
    alter table public.inventory
      add constraint inventory_product_id_fkey
      foreign key (product_id) references public.products (id) on delete cascade;
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.inventory'::regclass and conname = 'inventory_wh_prod_var_unique'
  ) then
    alter table public.inventory
      add constraint inventory_wh_prod_var_unique
      unique (warehouse_id, product_id, variant_id);
  end if;
end $$;

drop trigger if exists inventory_set_updated_at on public.inventory;
create trigger inventory_set_updated_at
  before update on public.inventory
  for each row execute function public.set_updated_at();

do $$ begin
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='inventory' and indexname='inventory_warehouse_id_idx') then
    create index inventory_warehouse_id_idx  on public.inventory (warehouse_id);
  end if;
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='inventory' and indexname='inventory_product_id_idx') then
    create index inventory_product_id_idx    on public.inventory (product_id);
  end if;
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='inventory' and indexname='inventory_variant_id_idx') then
    create index inventory_variant_id_idx    on public.inventory (variant_id);
  end if;
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='inventory' and indexname='inventory_product_sku_idx')
     and exists (select 1 from information_schema.columns where table_schema='public' and table_name='inventory' and column_name='product_sku')
  then
    create index inventory_product_sku_idx   on public.inventory (product_sku);
  end if;
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='inventory' and indexname='inventory_available_qty_idx')
     and exists (select 1 from information_schema.columns where table_schema='public' and table_name='inventory' and column_name='available_qty')
  then
    create index inventory_available_qty_idx on public.inventory (available_qty);
  end if;
end $$;

alter table public.inventory enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='inventory' and policyname='inventory_service_all') then
    create policy inventory_service_all on public.inventory for all to service_role using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='inventory' and policyname='inventory_auth_read') then
    create policy inventory_auth_read on public.inventory for select to authenticated using (true);
  end if;
end $$;

-- ============================================================
-- SECTION 5 — INVENTORY ADJUSTMENTS (audit log)
-- ============================================================

create table if not exists public.inventory_adjustments (
  id           bigint generated by default as identity primary key,
  inventory_id bigint,
  qty_change   integer not null default 0,
  reason       text    not null default 'other',
  notes        text,
  actor_id     uuid,
  created_at   timestamptz not null default now()
);

-- Add every column defensively — this is the table the earlier migration
-- may have created with different columns. The inventory_id column is the
-- one that caused ERROR 42703 on the original index creation.
alter table public.inventory_adjustments
  add column if not exists inventory_id bigint,
  add column if not exists qty_change   integer not null default 0,
  add column if not exists reason       text    not null default 'other',
  add column if not exists notes        text,
  add column if not exists actor_id     uuid,
  add column if not exists created_at   timestamptz not null default now();

-- Cast reason column to enum only if it is currently plain text
do $$ begin
  if not exists (
    select 1 from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_type  t on t.oid = a.atttypid
    where c.relnamespace = 'public'::regnamespace
      and c.relname  = 'inventory_adjustments'
      and a.attname  = 'reason'
      and t.typname  = 'adjustment_reason'
  ) then
    alter table public.inventory_adjustments
      alter column reason type public.adjustment_reason
      using reason::public.adjustment_reason;
  end if;
exception when others then null; end $$;

-- FK: inventory_id → inventory.id  (add only if absent)
do $$ begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.inventory_adjustments'::regclass
      and conname  = 'inventory_adjustments_inventory_id_fkey'
  ) then
    alter table public.inventory_adjustments
      add constraint inventory_adjustments_inventory_id_fkey
      foreign key (inventory_id) references public.inventory (id) on delete cascade;
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.inventory_adjustments'::regclass
      and conname  = 'inventory_adjustments_actor_id_fkey'
  ) then
    alter table public.inventory_adjustments
      add constraint inventory_adjustments_actor_id_fkey
      foreign key (actor_id) references auth.users (id) on delete set null;
  end if;
end $$;

-- Indexes — all guarded by column-existence check
do $$ begin
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='inventory_adjustments' and indexname='inv_adj_inventory_id_idx')
     and exists (select 1 from information_schema.columns where table_schema='public' and table_name='inventory_adjustments' and column_name='inventory_id')
  then
    create index inv_adj_inventory_id_idx on public.inventory_adjustments (inventory_id);
  end if;
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='inventory_adjustments' and indexname='inv_adj_created_at_idx')
     and exists (select 1 from information_schema.columns where table_schema='public' and table_name='inventory_adjustments' and column_name='created_at')
  then
    create index inv_adj_created_at_idx on public.inventory_adjustments (created_at desc);
  end if;
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='inventory_adjustments' and indexname='inv_adj_actor_id_idx')
     and exists (select 1 from information_schema.columns where table_schema='public' and table_name='inventory_adjustments' and column_name='actor_id')
  then
    create index inv_adj_actor_id_idx on public.inventory_adjustments (actor_id);
  end if;
end $$;

alter table public.inventory_adjustments enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='inventory_adjustments' and policyname='inventory_adjustments_inv_service_all') then
    create policy inventory_adjustments_inv_service_all on public.inventory_adjustments for all to service_role using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='inventory_adjustments' and policyname='inventory_adjustments_inv_auth_read') then
    create policy inventory_adjustments_inv_auth_read on public.inventory_adjustments for select to authenticated using (true);
  end if;
end $$;

-- ============================================================
-- SECTION 6 — STOCK TRANSFERS
-- ============================================================

create table if not exists public.stock_transfers (
  id                 bigint generated by default as identity primary key,
  from_warehouse_id  bigint,
  to_warehouse_id    bigint,
  product_id         bigint,
  variant_id         bigint,
  quantity           integer not null default 0,
  status             text    not null default 'pending',
  notes              text,
  initiated_by       uuid,
  initiated_at       timestamptz not null default now(),
  completed_at       timestamptz,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

alter table public.stock_transfers
  add column if not exists from_warehouse_id  bigint,
  add column if not exists to_warehouse_id    bigint,
  add column if not exists product_id         bigint,
  add column if not exists variant_id         bigint,
  add column if not exists quantity           integer not null default 0,
  add column if not exists status             text    not null default 'pending',
  add column if not exists notes              text,
  add column if not exists initiated_by       uuid,
  add column if not exists initiated_at       timestamptz not null default now(),
  add column if not exists completed_at       timestamptz,
  add column if not exists created_at         timestamptz not null default now(),
  add column if not exists updated_at         timestamptz not null default now();

-- Cast status to enum only if currently plain text
do $$ begin
  if not exists (
    select 1 from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_type  t on t.oid = a.atttypid
    where c.relnamespace = 'public'::regnamespace
      and c.relname = 'stock_transfers'
      and a.attname = 'status'
      and t.typname = 'transfer_status'
  ) then
    alter table public.stock_transfers
      alter column status type public.transfer_status
      using status::public.transfer_status;
  end if;
exception when others then null; end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conrelid='public.stock_transfers'::regclass and conname='stock_transfers_from_wh_fkey') then
    alter table public.stock_transfers add constraint stock_transfers_from_wh_fkey foreign key (from_warehouse_id) references public.warehouses (id) on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conrelid='public.stock_transfers'::regclass and conname='stock_transfers_to_wh_fkey') then
    alter table public.stock_transfers add constraint stock_transfers_to_wh_fkey foreign key (to_warehouse_id) references public.warehouses (id) on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conrelid='public.stock_transfers'::regclass and conname='stock_transfers_product_id_fkey') then
    alter table public.stock_transfers add constraint stock_transfers_product_id_fkey foreign key (product_id) references public.products (id) on delete cascade;
  end if;
  if not exists (select 1 from pg_constraint where conrelid='public.stock_transfers'::regclass and conname='stock_transfers_initiated_by_fkey') then
    alter table public.stock_transfers add constraint stock_transfers_initiated_by_fkey foreign key (initiated_by) references auth.users (id) on delete restrict;
  end if;
end $$;

drop trigger if exists stock_transfers_set_updated_at on public.stock_transfers;
create trigger stock_transfers_set_updated_at
  before update on public.stock_transfers
  for each row execute function public.set_updated_at();

do $$ begin
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='stock_transfers' and indexname='stock_transfers_from_wh_idx') then create index stock_transfers_from_wh_idx on public.stock_transfers (from_warehouse_id); end if;
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='stock_transfers' and indexname='stock_transfers_to_wh_idx') then create index stock_transfers_to_wh_idx on public.stock_transfers (to_warehouse_id); end if;
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='stock_transfers' and indexname='stock_transfers_product_id_idx') then create index stock_transfers_product_id_idx on public.stock_transfers (product_id); end if;
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='stock_transfers' and indexname='stock_transfers_status_idx') then create index stock_transfers_status_idx on public.stock_transfers (status); end if;
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='stock_transfers' and indexname='stock_transfers_initiated_by_idx')
     and exists (select 1 from information_schema.columns where table_schema='public' and table_name='stock_transfers' and column_name='initiated_by')
  then create index stock_transfers_initiated_by_idx on public.stock_transfers (initiated_by); end if;
end $$;

alter table public.stock_transfers enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='stock_transfers' and policyname='stock_transfers_service_all') then
    create policy stock_transfers_service_all on public.stock_transfers for all to service_role using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='stock_transfers' and policyname='stock_transfers_auth_read') then
    create policy stock_transfers_auth_read on public.stock_transfers for select to authenticated using (true);
  end if;
end $$;

-- ============================================================
-- SECTION 7 — PURCHASE ORDERS (Inventory-native)
-- ============================================================

create table if not exists public.purchase_orders (
  id            bigint generated by default as identity primary key,
  po_number     text    not null,
  vendor_id     bigint,
  warehouse_id  bigint,
  status        text    not null default 'draft',
  order_date    timestamptz not null default now(),
  expected_date date,
  subtotal      numeric(14,2) not null default 0,
  tax_amount    numeric(14,2) not null default 0,
  total_amount  numeric(14,2) not null default 0,
  notes         text,
  created_by    uuid,
  updated_by    uuid,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

do $$ begin
  if not exists (select 1 from pg_constraint where conrelid='public.purchase_orders'::regclass and conname='purchase_orders_po_number_key') then
    alter table public.purchase_orders add constraint purchase_orders_po_number_key unique (po_number);
  end if;
end $$;

alter table public.purchase_orders
  add column if not exists vendor_id     bigint,
  add column if not exists warehouse_id  bigint,
  add column if not exists order_date    timestamptz not null default now(),
  add column if not exists expected_date date,
  add column if not exists subtotal      numeric(14,2) not null default 0,
  add column if not exists tax_amount    numeric(14,2) not null default 0,
  add column if not exists total_amount  numeric(14,2) not null default 0,
  add column if not exists notes         text,
  add column if not exists created_by    uuid,
  add column if not exists updated_by    uuid,
  add column if not exists created_at    timestamptz not null default now(),
  add column if not exists updated_at    timestamptz not null default now();

-- Cast status to enum only if currently plain text
do $$ begin
  if not exists (
    select 1 from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_type  t on t.oid = a.atttypid
    where c.relnamespace = 'public'::regnamespace
      and c.relname = 'purchase_orders'
      and a.attname = 'status'
      and t.typname = 'po_status'
  ) then
    alter table public.purchase_orders
      alter column status type public.po_status
      using status::public.po_status;
  end if;
exception when others then null; end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conrelid='public.purchase_orders'::regclass and conname='purchase_orders_vendor_id_fkey') then
    alter table public.purchase_orders add constraint purchase_orders_vendor_id_fkey foreign key (vendor_id) references public.vendors (id) on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conrelid='public.purchase_orders'::regclass and conname='purchase_orders_warehouse_id_fkey') then
    alter table public.purchase_orders add constraint purchase_orders_warehouse_id_fkey foreign key (warehouse_id) references public.warehouses (id) on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conrelid='public.purchase_orders'::regclass and conname='purchase_orders_created_by_fkey') then
    alter table public.purchase_orders add constraint purchase_orders_created_by_fkey foreign key (created_by) references auth.users (id) on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conrelid='public.purchase_orders'::regclass and conname='purchase_orders_updated_by_fkey') then
    alter table public.purchase_orders add constraint purchase_orders_updated_by_fkey foreign key (updated_by) references auth.users (id) on delete restrict;
  end if;
end $$;

drop trigger if exists purchase_orders_inv_set_updated_at on public.purchase_orders;
create trigger purchase_orders_inv_set_updated_at
  before update on public.purchase_orders
  for each row execute function public.set_updated_at();

do $$ begin
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='purchase_orders' and indexname='po_vendor_id_idx')
     and exists (select 1 from information_schema.columns where table_schema='public' and table_name='purchase_orders' and column_name='vendor_id')
  then create index po_vendor_id_idx on public.purchase_orders (vendor_id); end if;
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='purchase_orders' and indexname='po_warehouse_id_idx')
     and exists (select 1 from information_schema.columns where table_schema='public' and table_name='purchase_orders' and column_name='warehouse_id')
  then create index po_warehouse_id_idx on public.purchase_orders (warehouse_id); end if;
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='purchase_orders' and indexname='po_status_idx') then create index po_status_idx on public.purchase_orders (status); end if;
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='purchase_orders' and indexname='po_order_date_idx')
     and exists (select 1 from information_schema.columns where table_schema='public' and table_name='purchase_orders' and column_name='order_date')
  then create index po_order_date_idx on public.purchase_orders (order_date desc); end if;
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='purchase_orders' and indexname='po_created_by_idx')
     and exists (select 1 from information_schema.columns where table_schema='public' and table_name='purchase_orders' and column_name='created_by')
  then create index po_created_by_idx on public.purchase_orders (created_by); end if;
end $$;

alter table public.purchase_orders enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='purchase_orders' and policyname='po_service_all') then
    create policy po_service_all on public.purchase_orders for all to service_role using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='purchase_orders' and policyname='po_auth_read') then
    create policy po_auth_read on public.purchase_orders for select to authenticated using (true);
  end if;
end $$;

-- ============================================================
-- SECTION 8 — PURCHASE ORDER ITEMS
-- ============================================================

create table if not exists public.purchase_order_items (
  id           bigint generated by default as identity primary key,
  po_id        bigint,
  product_id   bigint,
  variant_id   bigint,
  ordered_qty  integer not null default 1,
  received_qty integer not null default 0,
  damaged_qty  integer not null default 0,
  unit_cost    numeric(12,4) not null default 0,
  total_cost   numeric(14,4) not null default 0,
  hsn_code     text,
  notes        text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

alter table public.purchase_order_items
  add column if not exists po_id        bigint,
  add column if not exists product_id   bigint,
  add column if not exists variant_id   bigint,
  add column if not exists ordered_qty  integer not null default 1,
  add column if not exists received_qty integer not null default 0,
  add column if not exists damaged_qty  integer not null default 0,
  add column if not exists unit_cost    numeric(12,4) not null default 0,
  add column if not exists total_cost   numeric(14,4) not null default 0,
  add column if not exists hsn_code     text,
  add column if not exists notes        text,
  add column if not exists created_at   timestamptz not null default now(),
  add column if not exists updated_at   timestamptz not null default now();

do $$ begin
  if not exists (select 1 from pg_constraint where conrelid='public.purchase_order_items'::regclass and conname='po_items_po_id_fkey') then
    alter table public.purchase_order_items add constraint po_items_po_id_fkey foreign key (po_id) references public.purchase_orders (id) on delete cascade;
  end if;
  if not exists (select 1 from pg_constraint where conrelid='public.purchase_order_items'::regclass and conname='po_items_product_id_fkey') then
    alter table public.purchase_order_items add constraint po_items_product_id_fkey foreign key (product_id) references public.products (id) on delete restrict;
  end if;
end $$;

drop trigger if exists po_items_set_updated_at on public.purchase_order_items;
create trigger po_items_set_updated_at
  before update on public.purchase_order_items
  for each row execute function public.set_updated_at();

do $$ begin
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='purchase_order_items' and indexname='po_items_po_id_idx')
     and exists (select 1 from information_schema.columns where table_schema='public' and table_name='purchase_order_items' and column_name='po_id')
  then create index po_items_po_id_idx on public.purchase_order_items (po_id); end if;
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='purchase_order_items' and indexname='po_items_product_id_idx')
     and exists (select 1 from information_schema.columns where table_schema='public' and table_name='purchase_order_items' and column_name='product_id')
  then create index po_items_product_id_idx on public.purchase_order_items (product_id); end if;
  if not exists (select 1 from pg_indexes where schemaname='public' and tablename='purchase_order_items' and indexname='po_items_variant_id_idx')
     and exists (select 1 from information_schema.columns where table_schema='public' and table_name='purchase_order_items' and column_name='variant_id')
  then create index po_items_variant_id_idx on public.purchase_order_items (variant_id); end if;
end $$;

alter table public.purchase_order_items enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='purchase_order_items' and policyname='po_items_service_all') then
    create policy po_items_service_all on public.purchase_order_items for all to service_role using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='purchase_order_items' and policyname='po_items_auth_read') then
    create policy po_items_auth_read on public.purchase_order_items for select to authenticated using (true);
  end if;
end $$;

-- ============================================================
-- SECTION 9 — v_inventory_summary VIEW
-- ============================================================

create or replace view public.v_inventory_summary as
select
  inv.id,
  inv.warehouse_id,
  w.name                                                  as warehouse_name,
  inv.product_id,
  inv.product_name,
  inv.product_sku,
  inv.variant_id,
  inv.variant_sku,
  inv.size_label,
  inv.available_qty,
  inv.reserved_qty,
  inv.damaged_qty,
  inv.avg_cost_price,
  (inv.available_qty * inv.avg_cost_price)::numeric(14,4)  as inventory_value,
  case
    when inv.available_qty = 0                         then 'out_of_stock'
    when inv.available_qty <= inv.low_stock_threshold  then 'low_stock'
    else                                                    'in_stock'
  end::text                                               as stock_status,
  inv.low_stock_threshold
from public.inventory inv
join public.warehouses w on w.id = inv.warehouse_id;

-- ============================================================
-- SECTION 10 — RPC: adjust_inventory_stock
-- ============================================================

create or replace function public.adjust_inventory_stock(
  p_inventory_id bigint,
  p_qty_change   integer,
  p_reason       text,
  p_notes        text    default null,
  p_actor_id     uuid    default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current integer;
  v_new     integer;
begin
  select available_qty into v_current
  from public.inventory
  where id = p_inventory_id
  for update;

  if not found then
    raise exception 'inventory record % not found', p_inventory_id;
  end if;

  v_new := v_current + p_qty_change;

  if v_new < 0 then
    raise exception 'insufficient stock: current=%, change=%', v_current, p_qty_change;
  end if;

  update public.inventory
  set    available_qty = v_new,
         updated_at    = now()
  where  id = p_inventory_id;

  insert into public.inventory_adjustments
    (inventory_id, qty_change, reason, notes, actor_id)
  values
    (p_inventory_id, p_qty_change,
     p_reason::public.adjustment_reason,
     p_notes, p_actor_id);

  return v_new;
end;
$$;

-- ============================================================
-- SECTION 11 — RPC: transfer_inventory_stock
-- ============================================================

create or replace function public.transfer_inventory_stock(
  p_from_warehouse_id bigint,
  p_to_warehouse_id   bigint,
  p_product_id        bigint,
  p_variant_id        bigint  default null,
  p_quantity          integer default 0,
  p_notes             text    default null,
  p_actor_id          uuid    default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_from_inv_id bigint;
  v_to_inv_id   bigint;
  v_current     integer;
  v_transfer_id bigint;
begin
  if p_quantity <= 0 then
    raise exception 'transfer quantity must be greater than zero';
  end if;

  select id, available_qty into v_from_inv_id, v_current
  from public.inventory
  where warehouse_id = p_from_warehouse_id
    and product_id   = p_product_id
    and (variant_id  = p_variant_id or (variant_id is null and p_variant_id is null))
  for update;

  if not found then
    raise exception 'source inventory record not found for warehouse=%, product=%',
      p_from_warehouse_id, p_product_id;
  end if;

  if v_current < p_quantity then
    raise exception 'insufficient stock: available=%, requested=%', v_current, p_quantity;
  end if;

  update public.inventory
  set    available_qty = available_qty - p_quantity,
         updated_at    = now()
  where  id = v_from_inv_id;

  select id into v_to_inv_id
  from public.inventory
  where warehouse_id = p_to_warehouse_id
    and product_id   = p_product_id
    and (variant_id  = p_variant_id or (variant_id is null and p_variant_id is null));

  if found then
    update public.inventory
    set    available_qty = available_qty + p_quantity,
           updated_at    = now()
    where  id = v_to_inv_id;
  else
    insert into public.inventory
      (warehouse_id, product_id, variant_id,
       product_name, product_sku, variant_sku, size_label,
       available_qty, avg_cost_price, low_stock_threshold)
    select p_to_warehouse_id, product_id, variant_id,
           product_name, product_sku, variant_sku, size_label,
           p_quantity, avg_cost_price, low_stock_threshold
    from public.inventory
    where id = v_from_inv_id
    returning id into v_to_inv_id;
  end if;

  insert into public.stock_transfers
    (from_warehouse_id, to_warehouse_id, product_id, variant_id,
     quantity, status, notes, initiated_by, completed_at)
  values
    (p_from_warehouse_id, p_to_warehouse_id, p_product_id, p_variant_id,
     p_quantity, 'completed'::public.transfer_status,
     p_notes,
     coalesce(p_actor_id, '00000000-0000-0000-0000-000000000000'::uuid),
     now())
  returning id into v_transfer_id;

  return v_transfer_id;
end;
$$;

-- ============================================================
-- SECTION 12 — RPC: receive_purchase_order
-- ============================================================

create or replace function public.receive_purchase_order(
  p_po_id        bigint,
  p_receipts     jsonb,
  p_received_by  uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_receipt        jsonb;
  v_item           record;
  v_warehouse_id   bigint;
  v_inv_id         bigint;
  v_new_status     public.po_status;
  v_total_ordered  integer;
  v_total_received integer;
  v_good_qty       integer;
  v_dmg_qty        integer;
  v_rcv_cost       numeric(12,4);
begin
  select warehouse_id into v_warehouse_id
  from public.purchase_orders
  where id = p_po_id
    and status not in ('received', 'cancelled')
  for update;

  if not found then
    raise exception 'purchase order % not found or not receivable', p_po_id;
  end if;

  for v_receipt in select * from jsonb_array_elements(p_receipts)
  loop
    select * into v_item
    from public.purchase_order_items
    where id    = (v_receipt->>'item_id')::bigint
      and po_id = p_po_id
    for update;

    if not found then
      raise exception 'purchase order item % not found for po %',
        v_receipt->>'item_id', p_po_id;
    end if;

    v_good_qty := (v_receipt->>'received_qty')::integer;
    v_dmg_qty  := coalesce((v_receipt->>'damaged_qty')::integer, 0);
    v_rcv_cost := coalesce((v_receipt->>'unit_cost')::numeric, v_item.unit_cost);

    update public.purchase_order_items
    set received_qty = received_qty + v_good_qty,
        damaged_qty  = damaged_qty  + v_dmg_qty,
        unit_cost    = v_rcv_cost,
        total_cost   = v_item.ordered_qty * v_rcv_cost,
        updated_at   = now()
    where id = v_item.id;

    -- Resolve inventory row
    select id into v_inv_id
    from public.inventory
    where warehouse_id = v_warehouse_id
      and product_id   = v_item.product_id
      and (variant_id  = v_item.variant_id
           or (variant_id is null and v_item.variant_id is null))
    for update;

    if found then
      update public.inventory
      set available_qty  = available_qty + v_good_qty - v_dmg_qty,
          damaged_qty    = damaged_qty   + v_dmg_qty,
          avg_cost_price = case
            when (available_qty + v_good_qty - v_dmg_qty) > 0
            then (
              (avg_cost_price * available_qty)
              + (v_rcv_cost * (v_good_qty - v_dmg_qty))
            ) / (available_qty + v_good_qty - v_dmg_qty)
            else avg_cost_price
          end,
          updated_at     = now()
      where id = v_inv_id;
    else
      insert into public.inventory
        (warehouse_id, product_id, variant_id,
         product_name, product_sku,
         available_qty, damaged_qty, avg_cost_price)
      select
        v_warehouse_id, v_item.product_id, v_item.variant_id,
        p.name,
        coalesce(pv.sku, p.sku),
        greatest(v_good_qty - v_dmg_qty, 0),
        v_dmg_qty,
        v_rcv_cost
      from public.products p
      left join public.product_variants pv on pv.id = v_item.variant_id
      where p.id = v_item.product_id
      returning id into v_inv_id;
    end if;

    insert into public.inventory_adjustments
      (inventory_id, qty_change, reason, notes, actor_id)
    values (
      v_inv_id,
      v_good_qty - v_dmg_qty,
      'vendor_credit'::public.adjustment_reason,
      coalesce(v_receipt->>'notes', 'PO receipt for po_id=' || p_po_id),
      p_received_by
    );
  end loop;

  select sum(ordered_qty), sum(received_qty)
  into v_total_ordered, v_total_received
  from public.purchase_order_items
  where po_id = p_po_id;

  v_new_status :=
    case
      when v_total_received = 0               then 'sent'
      when v_total_received >= v_total_ordered then 'received'
      else                                         'partial'
    end::public.po_status;

  update public.purchase_orders
  set status     = v_new_status,
      updated_by = p_received_by,
      updated_at = now()
  where id = p_po_id;
end;
$$;

-- ============================================================
-- SECTION 13 — SCHEMA CACHE RELOAD
-- After applying, run:
--   SELECT pg_notify('pgrst', 'reload schema');
-- ============================================================
