-- ============================================================
-- INVENTORY VENDOR DOMAIN
-- 20260803000000_inventory_vendor_domain.sql
--
-- Creates the complete set of tables, views, and RPC functions
-- required by InventoryService (src/services/inventory.service.ts)
-- and the /inventory/purchase-orders Next.js routes.
--
-- Objects created:
--   public.warehouses
--   public.vendors
--   public.inventory
--   public.inventory_adjustments
--   public.stock_transfers
--   public.purchase_orders         (Inventory-native PO, separate from
--                                   fulfillment purchase_orders in catchup)
--   public.purchase_order_items    (Inventory-native)
--   public.v_inventory_summary     (view)
--   adjust_inventory_stock()       (RPC)
--   transfer_inventory_stock()     (RPC)
--   receive_purchase_order()       (RPC)
--
-- Safety guarantees:
--   * CREATE TABLE        → IF NOT EXISTS
--   * ALTER TABLE ADD COL → ADD COLUMN IF NOT EXISTS
--   * CREATE INDEX        → IF NOT EXISTS
--   * CREATE TYPE / enum  → DO $$ BEGIN ... EXCEPTION WHEN duplicate_object
--   * CREATE POLICY       → guarded by pg_policies existence check
--   * CREATE OR REPLACE   → safe for functions and views
--   * No DROP TABLE / DROP COLUMN
--   * No data mutations
--   * Idempotent: safe to run more than once
-- ============================================================

-- ============================================================
-- SECTION 1 — ENUMS
-- ============================================================

do $$ begin
  create type public.po_status as enum
    ('draft', 'sent', 'partial', 'received', 'cancelled');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.transfer_status as enum
    ('pending', 'in_transit', 'completed', 'cancelled');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.stock_status as enum
    ('in_stock', 'low_stock', 'out_of_stock');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.adjustment_reason as enum (
    'cycle_count', 'damage_write_off', 'damage_recovery',
    'theft_loss', 'expiry', 'found_surplus',
    'vendor_credit', 'sample_used', 'other'
  );
exception when duplicate_object then null; end $$;

-- ============================================================
-- SECTION 2 — WAREHOUSES
--   Consumed by: listWarehouses(), createPurchaseOrder(),
--                listPurchaseOrders(), v_inventory_summary
-- ============================================================

create table if not exists public.warehouses (
  id         bigint generated by default as identity primary key,
  name       text    not null unique,
  code       text    not null unique,
  address    text,
  is_default boolean not null default false,
  is_active  boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists warehouses_set_updated_at on public.warehouses;
create trigger warehouses_set_updated_at
  before update on public.warehouses
  for each row execute function public.set_updated_at();

create index if not exists warehouses_is_active_idx  on public.warehouses (is_active);
create index if not exists warehouses_is_default_idx on public.warehouses (is_default);

alter table public.warehouses enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'warehouses'
    and policyname = 'warehouses_service_all'
  ) then
    create policy warehouses_service_all on public.warehouses
      for all to service_role using (true) with check (true);
  end if;
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'warehouses'
    and policyname = 'warehouses_auth_read'
  ) then
    create policy warehouses_auth_read on public.warehouses
      for select to authenticated using (true);
  end if;
end $$;

-- ============================================================
-- SECTION 3 — VENDORS
--   Consumed by: listVendors(), listPurchaseOrders(),
--                getPurchaseOrder(), createPurchaseOrder()
-- ============================================================

create table if not exists public.vendors (
  id            bigint generated by default as identity primary key,
  name          text    not null,
  code          text    not null unique,
  gstin         text,
  email         text,
  phone         text,
  address       text,
  payment_terms integer not null default 30
                  check (payment_terms >= 0),
  is_active     boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

drop trigger if exists vendors_set_updated_at on public.vendors;
create trigger vendors_set_updated_at
  before update on public.vendors
  for each row execute function public.set_updated_at();

create index if not exists vendors_is_active_idx on public.vendors (is_active);
create index if not exists vendors_name_idx      on public.vendors (name);
create index if not exists vendors_code_idx      on public.vendors (code);

alter table public.vendors enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'vendors'
    and policyname = 'vendors_service_all'
  ) then
    create policy vendors_service_all on public.vendors
      for all to service_role using (true) with check (true);
  end if;
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'vendors'
    and policyname = 'vendors_auth_read'
  ) then
    create policy vendors_auth_read on public.vendors
      for select to authenticated using (true);
  end if;
end $$;

-- ============================================================
-- SECTION 4 — INVENTORY (stock ledger)
--   Consumed by: search() → v_inventory_summary,
--                adjustStock() → adjust_inventory_stock(),
--                transferStock() → transfer_inventory_stock()
-- ============================================================

create table if not exists public.inventory (
  id                  bigint generated by default as identity primary key,
  warehouse_id        bigint  not null references public.warehouses (id) on delete restrict,
  product_id          bigint  not null references public.products   (id) on delete cascade,
  variant_id          bigint,                                -- null = product-level stock
  product_name        text    not null,
  product_sku         text    not null,
  variant_sku         text,
  size_label          text,
  available_qty       integer not null default 0 check (available_qty >= 0),
  reserved_qty        integer not null default 0 check (reserved_qty  >= 0),
  damaged_qty         integer not null default 0 check (damaged_qty   >= 0),
  avg_cost_price      numeric(12,4) not null default 0 check (avg_cost_price >= 0),
  low_stock_threshold integer not null default 10 check (low_stock_threshold >= 0),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  unique (warehouse_id, product_id, variant_id)
);

drop trigger if exists inventory_set_updated_at on public.inventory;
create trigger inventory_set_updated_at
  before update on public.inventory
  for each row execute function public.set_updated_at();

create index if not exists inventory_warehouse_id_idx    on public.inventory (warehouse_id);
create index if not exists inventory_product_id_idx      on public.inventory (product_id);
create index if not exists inventory_variant_id_idx      on public.inventory (variant_id);
create index if not exists inventory_product_sku_idx     on public.inventory (product_sku);
create index if not exists inventory_available_qty_idx   on public.inventory (available_qty);

alter table public.inventory enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'inventory'
    and policyname = 'inventory_service_all'
  ) then
    create policy inventory_service_all on public.inventory
      for all to service_role using (true) with check (true);
  end if;
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'inventory'
    and policyname = 'inventory_auth_read'
  ) then
    create policy inventory_auth_read on public.inventory
      for select to authenticated using (true);
  end if;
end $$;

-- ============================================================
-- SECTION 5 — INVENTORY ADJUSTMENTS (audit log)
--   Consumed by: adjust_inventory_stock() RPC
-- ============================================================

create table if not exists public.inventory_adjustments (
  id           bigint generated by default as identity primary key,
  inventory_id bigint  not null references public.inventory (id) on delete cascade,
  qty_change   integer not null,
  reason       public.adjustment_reason not null default 'other',
  notes        text,
  actor_id     uuid references auth.users (id) on delete set null,
  created_at   timestamptz not null default now()
);

create index if not exists inv_adj_inventory_id_idx on public.inventory_adjustments (inventory_id);
create index if not exists inv_adj_created_at_idx   on public.inventory_adjustments (created_at desc);
create index if not exists inv_adj_actor_id_idx     on public.inventory_adjustments (actor_id);

alter table public.inventory_adjustments enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'inventory_adjustments'
    and policyname = 'inventory_adjustments_inv_service_all'
  ) then
    create policy inventory_adjustments_inv_service_all on public.inventory_adjustments
      for all to service_role using (true) with check (true);
  end if;
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'inventory_adjustments'
    and policyname = 'inventory_adjustments_inv_auth_read'
  ) then
    create policy inventory_adjustments_inv_auth_read on public.inventory_adjustments
      for select to authenticated using (true);
  end if;
end $$;

-- ============================================================
-- SECTION 6 — STOCK TRANSFERS
--   Consumed by: transfer_inventory_stock() RPC
-- ============================================================

create table if not exists public.stock_transfers (
  id                 bigint generated by default as identity primary key,
  from_warehouse_id  bigint  not null references public.warehouses (id) on delete restrict,
  to_warehouse_id    bigint  not null references public.warehouses (id) on delete restrict,
  product_id         bigint  not null references public.products   (id) on delete cascade,
  variant_id         bigint,
  quantity           integer not null check (quantity > 0),
  status             public.transfer_status not null default 'pending',
  notes              text,
  initiated_by       uuid    not null references auth.users (id) on delete restrict,
  initiated_at       timestamptz not null default now(),
  completed_at       timestamptz,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

drop trigger if exists stock_transfers_set_updated_at on public.stock_transfers;
create trigger stock_transfers_set_updated_at
  before update on public.stock_transfers
  for each row execute function public.set_updated_at();

create index if not exists stock_transfers_from_wh_idx   on public.stock_transfers (from_warehouse_id);
create index if not exists stock_transfers_to_wh_idx     on public.stock_transfers (to_warehouse_id);
create index if not exists stock_transfers_product_id_idx on public.stock_transfers (product_id);
create index if not exists stock_transfers_status_idx    on public.stock_transfers (status);
create index if not exists stock_transfers_initiated_by_idx on public.stock_transfers (initiated_by);

alter table public.stock_transfers enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'stock_transfers'
    and policyname = 'stock_transfers_service_all'
  ) then
    create policy stock_transfers_service_all on public.stock_transfers
      for all to service_role using (true) with check (true);
  end if;
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'stock_transfers'
    and policyname = 'stock_transfers_auth_read'
  ) then
    create policy stock_transfers_auth_read on public.stock_transfers
      for select to authenticated using (true);
  end if;
end $$;

-- ============================================================
-- SECTION 7 — PURCHASE ORDERS (Inventory-native)
--
--   NOTE: The catchup migration (20260802235900) also created a
--   public.purchase_orders table for the fulfillment module.
--   This table is intentionally separate: the fulfillment PO
--   links to inventory_locations; the inventory-native PO links
--   to warehouses + vendors and carries the full purchasing
--   workflow (subtotal, tax_amount, total_amount, order_date,
--   received status via RPC).
--
--   CREATE TABLE IF NOT EXISTS means if either table was
--   created first, the second migration's statement is a no-op
--   on the other. Because both use IF NOT EXISTS and the
--   catchup migration will have already created the table, this
--   section ADD COLUMNs any columns that may be missing.
-- ============================================================

create table if not exists public.purchase_orders (
  id            bigint generated by default as identity primary key,
  po_number     text    not null unique,
  vendor_id     bigint  not null references public.vendors    (id) on delete restrict,
  warehouse_id  bigint  not null references public.warehouses (id) on delete restrict,
  status        public.po_status not null default 'draft',
  order_date    timestamptz not null default now(),
  expected_date date,
  subtotal      numeric(14,2) not null default 0 check (subtotal >= 0),
  tax_amount    numeric(14,2) not null default 0 check (tax_amount >= 0),
  total_amount  numeric(14,2) not null default 0 check (total_amount >= 0),
  notes         text,
  created_by    uuid not null references auth.users (id) on delete restrict,
  updated_by    uuid not null references auth.users (id) on delete restrict,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- If the fulfillment catchup already created purchase_orders without the
-- inventory-specific columns, add them safely.
alter table public.purchase_orders
  add column if not exists vendor_id     bigint references public.vendors    (id) on delete restrict,
  add column if not exists warehouse_id  bigint references public.warehouses (id) on delete restrict,
  add column if not exists order_date    timestamptz,
  add column if not exists subtotal      numeric(14,2),
  add column if not exists tax_amount    numeric(14,2),
  add column if not exists total_amount  numeric(14,2),
  add column if not exists updated_by    uuid references auth.users (id) on delete restrict;

drop trigger if exists purchase_orders_inv_set_updated_at on public.purchase_orders;
create trigger purchase_orders_inv_set_updated_at
  before update on public.purchase_orders
  for each row execute function public.set_updated_at();

create index if not exists po_vendor_id_idx      on public.purchase_orders (vendor_id);
create index if not exists po_warehouse_id_idx   on public.purchase_orders (warehouse_id);
create index if not exists po_status_idx         on public.purchase_orders (status);
create index if not exists po_order_date_idx     on public.purchase_orders (order_date desc);
create index if not exists po_created_by_idx     on public.purchase_orders (created_by);

alter table public.purchase_orders enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'purchase_orders'
    and policyname = 'po_service_all'
  ) then
    create policy po_service_all on public.purchase_orders
      for all to service_role using (true) with check (true);
  end if;
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'purchase_orders'
    and policyname = 'po_auth_read'
  ) then
    create policy po_auth_read on public.purchase_orders
      for select to authenticated using (true);
  end if;
end $$;

-- ============================================================
-- SECTION 8 — PURCHASE ORDER ITEMS (Inventory-native)
--   Consumed by: createPurchaseOrder(), getPurchaseOrder(),
--                listPurchaseOrders(), receive_purchase_order()
-- ============================================================

create table if not exists public.purchase_order_items (
  id           bigint generated by default as identity primary key,
  po_id        bigint  not null references public.purchase_orders (id) on delete cascade,
  product_id   bigint  not null references public.products (id) on delete restrict,
  variant_id   bigint,
  ordered_qty  integer not null check (ordered_qty  > 0),
  received_qty integer not null default 0 check (received_qty >= 0),
  damaged_qty  integer not null default 0 check (damaged_qty  >= 0),
  unit_cost    numeric(12,4) not null check (unit_cost >= 0),
  total_cost   numeric(14,4) not null default 0 check (total_cost >= 0),
  hsn_code     text,
  notes        text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

drop trigger if exists po_items_set_updated_at on public.purchase_order_items;
create trigger po_items_set_updated_at
  before update on public.purchase_order_items
  for each row execute function public.set_updated_at();

create index if not exists po_items_po_id_idx      on public.purchase_order_items (po_id);
create index if not exists po_items_product_id_idx on public.purchase_order_items (product_id);
create index if not exists po_items_variant_id_idx on public.purchase_order_items (variant_id);

alter table public.purchase_order_items enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'purchase_order_items'
    and policyname = 'po_items_service_all'
  ) then
    create policy po_items_service_all on public.purchase_order_items
      for all to service_role using (true) with check (true);
  end if;
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'purchase_order_items'
    and policyname = 'po_items_auth_read'
  ) then
    create policy po_items_auth_read on public.purchase_order_items
      for select to authenticated using (true);
  end if;
end $$;

-- ============================================================
-- SECTION 9 — v_inventory_summary VIEW
--   Consumed by: InventoryService.search() and getLowStockReport()
--   Matches InventorySummaryRow interface exactly.
-- ============================================================

create or replace view public.v_inventory_summary as
select
  inv.id,
  inv.warehouse_id,
  w.name                                           as warehouse_name,
  inv.product_id,
  inv.product_name,
  inv.product_sku,
  inv.variant_id,
  inv.variant_sku,
  inv.size_label,
  inv.available_qty,
  inv.reserved_qty,
  inv.damaged_qty,
  inv.avg_cost_price,
  (inv.available_qty * inv.avg_cost_price)::numeric(14,4) as inventory_value,
  case
    when inv.available_qty = 0                            then 'out_of_stock'
    when inv.available_qty <= inv.low_stock_threshold     then 'low_stock'
    else                                                       'in_stock'
  end::text                                        as stock_status,
  inv.low_stock_threshold
from public.inventory inv
join public.warehouses w on w.id = inv.warehouse_id;

-- ============================================================
-- SECTION 10 — RPC: adjust_inventory_stock
--   Called by: InventoryService.adjustStock()
--   Parameters:
--     p_inventory_id  bigint
--     p_qty_change    integer   (positive = add, negative = deduct)
--     p_reason        text      (maps to adjustment_reason enum)
--     p_notes         text
--     p_actor_id      uuid
--   Returns: bigint (new available_qty)
-- ============================================================

create or replace function public.adjust_inventory_stock(
  p_inventory_id bigint,
  p_qty_change   integer,
  p_reason       text,
  p_notes        text    default null,
  p_actor_id     uuid    default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current integer;
  v_new     integer;
begin
  -- Lock the row
  select available_qty into v_current
  from public.inventory
  where id = p_inventory_id
  for update;

  if not found then
    raise exception 'inventory record % not found', p_inventory_id;
  end if;

  v_new := v_current + p_qty_change;

  if v_new < 0 then
    raise exception 'insufficient stock: current=%, change=%', v_current, p_qty_change;
  end if;

  update public.inventory
  set    available_qty = v_new,
         updated_at    = now()
  where  id = p_inventory_id;

  insert into public.inventory_adjustments
    (inventory_id, qty_change, reason, notes, actor_id)
  values
    (p_inventory_id, p_qty_change,
     p_reason::public.adjustment_reason,
     p_notes, p_actor_id);

  return v_new;
end;
$$;

-- ============================================================
-- SECTION 11 — RPC: transfer_inventory_stock
--   Called by: InventoryService.transferStock()
--   Parameters:
--     p_from_warehouse_id  bigint
--     p_to_warehouse_id    bigint
--     p_product_id         bigint
--     p_variant_id         bigint (nullable)
--     p_quantity           integer
--     p_notes              text
--     p_actor_id           uuid
--   Returns: bigint (new stock_transfer id)
-- ============================================================

create or replace function public.transfer_inventory_stock(
  p_from_warehouse_id bigint,
  p_to_warehouse_id   bigint,
  p_product_id        bigint,
  p_variant_id        bigint  default null,
  p_quantity          integer default 0,
  p_notes             text    default null,
  p_actor_id          uuid    default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_from_inv_id bigint;
  v_to_inv_id   bigint;
  v_current     integer;
  v_transfer_id bigint;
begin
  if p_quantity <= 0 then
    raise exception 'transfer quantity must be greater than zero';
  end if;

  -- Resolve source inventory record
  select id, available_qty into v_from_inv_id, v_current
  from public.inventory
  where warehouse_id = p_from_warehouse_id
    and product_id   = p_product_id
    and (variant_id  = p_variant_id or (variant_id is null and p_variant_id is null))
  for update;

  if not found then
    raise exception 'source inventory record not found for warehouse=%, product=%',
      p_from_warehouse_id, p_product_id;
  end if;

  if v_current < p_quantity then
    raise exception 'insufficient stock at source warehouse: available=%, requested=%',
      v_current, p_quantity;
  end if;

  -- Deduct from source
  update public.inventory
  set    available_qty = available_qty - p_quantity,
         updated_at    = now()
  where  id = v_from_inv_id;

  -- Resolve or create destination inventory record
  select id into v_to_inv_id
  from public.inventory
  where warehouse_id = p_to_warehouse_id
    and product_id   = p_product_id
    and (variant_id  = p_variant_id or (variant_id is null and p_variant_id is null));

  if found then
    update public.inventory
    set    available_qty = available_qty + p_quantity,
           updated_at    = now()
    where  id = v_to_inv_id;
  else
    -- Inherit product/variant metadata from source record
    insert into public.inventory
      (warehouse_id, product_id, variant_id,
       product_name, product_sku, variant_sku, size_label,
       available_qty, avg_cost_price, low_stock_threshold)
    select p_to_warehouse_id, product_id, variant_id,
           product_name, product_sku, variant_sku, size_label,
           p_quantity, avg_cost_price, low_stock_threshold
    from public.inventory
    where id = v_from_inv_id
    returning id into v_to_inv_id;
  end if;

  -- Record the transfer
  insert into public.stock_transfers
    (from_warehouse_id, to_warehouse_id, product_id, variant_id,
     quantity, status, notes, initiated_by, completed_at)
  values
    (p_from_warehouse_id, p_to_warehouse_id, p_product_id, p_variant_id,
     p_quantity, 'completed', p_notes, coalesce(p_actor_id, '00000000-0000-0000-0000-000000000000'::uuid), now())
  returning id into v_transfer_id;

  return v_transfer_id;
end;
$$;

-- ============================================================
-- SECTION 12 — RPC: receive_purchase_order
--   Called by: InventoryService.receivePurchaseOrder()
--   Parameters:
--     p_po_id        bigint
--     p_receipts     jsonb   array of {item_id, received_qty, damaged_qty,
--                                       unit_cost, notes}
--     p_received_by  uuid
--   Updates purchase_order_items quantities, recalculates PO status,
--   and credits the inventory for the destination warehouse.
-- ============================================================

create or replace function public.receive_purchase_order(
  p_po_id        bigint,
  p_receipts     jsonb,
  p_received_by  uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_receipt     jsonb;
  v_item        record;
  v_warehouse_id bigint;
  v_inv_id       bigint;
  v_new_status   public.po_status;
  v_total_ordered  integer;
  v_total_received integer;
begin
  -- Lock PO row and fetch warehouse
  select warehouse_id into v_warehouse_id
  from public.purchase_orders
  where id = p_po_id
    and status not in ('received', 'cancelled')
  for update;

  if not found then
    raise exception 'purchase order % not found or not receivable', p_po_id;
  end if;

  -- Process each receipt line
  for v_receipt in select * from jsonb_array_elements(p_receipts)
  loop
    select * into v_item
    from public.purchase_order_items
    where id = (v_receipt->>'item_id')::bigint
      and po_id = p_po_id
    for update;

    if not found then
      raise exception 'purchase order item % not found for po %',
        v_receipt->>'item_id', p_po_id;
    end if;

    update public.purchase_order_items
    set received_qty = received_qty + (v_receipt->>'received_qty')::integer,
        damaged_qty  = damaged_qty  + coalesce((v_receipt->>'damaged_qty')::integer, 0),
        unit_cost    = coalesce((v_receipt->>'unit_cost')::numeric, unit_cost),
        total_cost   = ordered_qty * coalesce((v_receipt->>'unit_cost')::numeric, unit_cost),
        updated_at   = now()
    where id = v_item.id;

    -- Credit the inventory for good (non-damaged) received qty
    select id into v_inv_id
    from public.inventory
    where warehouse_id = v_warehouse_id
      and product_id   = v_item.product_id
      and (variant_id  = v_item.variant_id
           or (variant_id is null and v_item.variant_id is null))
    for update;

    if found then
      update public.inventory
      set available_qty = available_qty
                        + (v_receipt->>'received_qty')::integer
                        - coalesce((v_receipt->>'damaged_qty')::integer, 0),
          damaged_qty   = damaged_qty
                        + coalesce((v_receipt->>'damaged_qty')::integer, 0),
          avg_cost_price = case
            when (available_qty + (v_receipt->>'received_qty')::integer
                  - coalesce((v_receipt->>'damaged_qty')::integer, 0)) > 0
            then (
              (avg_cost_price * available_qty)
              + (coalesce((v_receipt->>'unit_cost')::numeric, unit_cost)
                 * ((v_receipt->>'received_qty')::integer
                    - coalesce((v_receipt->>'damaged_qty')::integer, 0)))
            ) / (
              available_qty
              + (v_receipt->>'received_qty')::integer
              - coalesce((v_receipt->>'damaged_qty')::integer, 0)
            )
            else avg_cost_price
          end,
          updated_at    = now()
      where id = v_inv_id;
    else
      -- Create new inventory record for this warehouse + product
      insert into public.inventory
        (warehouse_id, product_id, variant_id,
         product_name, product_sku,
         available_qty, damaged_qty, avg_cost_price)
      select
        v_warehouse_id, v_item.product_id, v_item.variant_id,
        p.name, coalesce(pv.sku, p.sku),
        greatest((v_receipt->>'received_qty')::integer
                 - coalesce((v_receipt->>'damaged_qty')::integer, 0), 0),
        coalesce((v_receipt->>'damaged_qty')::integer, 0),
        coalesce((v_receipt->>'unit_cost')::numeric, v_item.unit_cost)
      from public.products p
      left join public.product_variants pv
        on pv.id = v_item.variant_id
      where p.id = v_item.product_id;
    end if;

    -- Adjustment log
    insert into public.inventory_adjustments
      (inventory_id, qty_change, reason, notes, actor_id)
    values (
      coalesce(v_inv_id,
        (select id from public.inventory
         where warehouse_id = v_warehouse_id
           and product_id   = v_item.product_id
           and (variant_id  = v_item.variant_id
                or (variant_id is null and v_item.variant_id is null))
         limit 1)
      ),
      (v_receipt->>'received_qty')::integer
        - coalesce((v_receipt->>'damaged_qty')::integer, 0),
      'vendor_credit',
      coalesce(v_receipt->>'notes', 'PO receipt for po_id=' || p_po_id),
      p_received_by
    );
  end loop;

  -- Recalculate PO status
  select
    sum(ordered_qty),
    sum(received_qty)
  into v_total_ordered, v_total_received
  from public.purchase_order_items
  where po_id = p_po_id;

  v_new_status :=
    case
      when v_total_received = 0               then 'sent'
      when v_total_received >= v_total_ordered then 'received'
      else                                         'partial'
    end::public.po_status;

  update public.purchase_orders
  set status     = v_new_status,
      updated_by = p_received_by,
      updated_at = now()
  where id = p_po_id;
end;
$$;

-- ============================================================
-- SECTION 13 — SCHEMA CACHE RELOAD HINT
-- ============================================================
-- After applying this migration run:
--   SELECT pg_notify('pgrst', 'reload schema');
-- or reload via Dashboard → Settings → API → Reload schema
-- ============================================================
