-- Bottom type attribute.
--
-- The catalogue sells palazzos, culottes, tulip pants, salwars and pant sets,
-- and there was nowhere to record which: no attribute table, no column, no
-- field in the product form. The information lived only inside product names
-- ("...with White Tulip Pants"), so it could not be filtered, faceted or shown
-- as a spec.
--
-- Mirrors the existing attr_* tables exactly — same columns, same RLS shape —
-- so it behaves identically to fabric, neck, work and the rest.

create table if not exists public.attr_bottom (
  id   bigint generated by default as identity primary key,
  name text   not null unique,
  slug text   not null unique,
  display_order integer not null default 0,
  active boolean not null default true
);

alter table public.attr_bottom enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'attr_bottom'
      and policyname = 'attr_bottom_public_read'
  ) then
    create policy attr_bottom_public_read on public.attr_bottom for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'attr_bottom'
      and policyname = 'attr_bottom_service_write'
  ) then
    create policy attr_bottom_service_write on public.attr_bottom
      for all to service_role using (true) with check (true);
  end if;
end $$;

-- Nullable on purpose: a kurti or top has no bottom, and existing products
-- must not be invalidated by this column appearing.
alter table public.products
  add column if not exists attr_bottom_id bigint references public.attr_bottom(id);

create index if not exists idx_products_attr_bottom_id
  on public.products (attr_bottom_id);

-- Seed the vocabulary. `on conflict do nothing` keeps this migration safe to
-- re-run and safe to apply after the options have been added by other means.
insert into public.attr_bottom (name, slug, display_order) values
  ('Palazzo',          'palazzo',          1),
  ('Straight Pant',    'straight-pant',    2),
  ('Cigarette Pant',   'cigarette-pant',   3),
  ('Tulip Pant',       'tulip-pant',       4),
  ('Parallel Pant',    'parallel-pant',    5),
  ('Ankle Pant',       'ankle-pant',       6),
  ('Culotte',          'culotte',          7),
  ('Sharara',          'sharara',          8),
  ('Garara',           'garara',           9),
  ('Dhoti Pant',       'dhoti-pant',      10),
  ('Patiala',          'patiala',         11),
  ('Churidar',         'churidar',        12),
  ('Salwar',           'salwar',          13),
  ('Farsi Salwar',     'farsi-salwar',    14),
  ('Afghani Salwar',   'afghani-salwar',  15),
  ('Harem Pant',       'harem-pant',      16),
  ('Skirt',            'skirt',           17),
  ('Lehenga',          'lehenga',         18),
  ('Trouser',          'trouser',         19)
on conflict (slug) do nothing;
