-- ============================================================
-- PRODUCT V2 TABLES CATCH-UP
-- 20260803_product_v2_tables_catchup.sql
--
-- Purpose: idempotent creation / column-addition for every
--          Product V2 table that services query but that was
--          not yet applied to production because the V2
--          foundation migration was only partially applied.
--
-- Safe on:
--   * clean database        (IF NOT EXISTS everywhere)
--   * partially migrated DB (ADD COLUMN IF NOT EXISTS)
--   * current production DB (no data loss, no drops)
--
-- FK dependency order (each table created before it is referenced):
--   auth.users             — Supabase built-in, always present
--   public.products        — created by 20260702001523_initial_schema
--   public.size_master     — created by 20260802235900 catchup
--   public.tags            — created in Section 1 of THIS file
--   public.product_images  — Section 2
--   public.product_variants — Section 3
--   public.product_tags    — Section 4  (references products + tags)
--   public.product_audit_log — Section 5
-- ============================================================

-- ============================================================
-- 0. HELPER — ensure set_updated_at() exists
-- ============================================================
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ============================================================
-- 1. ENUM TYPES (guard with EXCEPTION WHEN duplicate_object)
-- ============================================================

do $$
begin
  create type public.product_image_type as enum ('primary', 'gallery', 'zoom');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.variant_status as enum ('active', 'inactive', 'out_of_stock');
exception
  when duplicate_object then null;
end $$;

-- ============================================================
-- 2. TAGS
--    Must be created BEFORE product_tags which FKs into it.
-- ============================================================

create table if not exists public.tags (
  id            bigint generated by default as identity primary key,
  name          text    not null,
  slug          text    not null,
  active        boolean not null default true,
  display_order integer not null default 0,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint tags_name_key unique (name),
  constraint tags_slug_key unique (slug)
);

drop trigger if exists tags_set_updated_at on public.tags;
create trigger tags_set_updated_at
  before update on public.tags
  for each row execute function public.set_updated_at();

create index if not exists tags_slug_idx         on public.tags (slug);
create index if not exists tags_active_idx        on public.tags (active);
create index if not exists tags_display_order_idx on public.tags (display_order);

alter table public.tags enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'tags'
      and policyname = 'tags_public_read'
  ) then
    create policy tags_public_read
      on public.tags for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'tags'
      and policyname = 'tags_service_all'
  ) then
    create policy tags_service_all
      on public.tags for all to service_role
      using (true) with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'tags'
      and policyname = 'tags_admin_write'
  ) then
    create policy tags_admin_write
      on public.tags for all to authenticated
      using (
        (auth.jwt() ->> 'role') = 'admin'
        or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
      )
      with check (
        (auth.jwt() ->> 'role') = 'admin'
        or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
      );
  end if;
end $$;

-- ============================================================
-- 3. PRODUCT IMAGES
-- ============================================================

create table if not exists public.product_images (
  id          bigint generated by default as identity primary key,
  product_id  bigint not null references public.products (id) on delete cascade,
  image_type  public.product_image_type not null default 'gallery',
  url         text   not null,
  alt         text,
  sort_order  integer not null default 0,
  dam_asset_id uuid,                    -- optional link to dam_assets.id
  created_at  timestamptz not null default now()
);

create index if not exists product_images_product_id_idx
  on public.product_images (product_id);
create index if not exists product_images_type_idx
  on public.product_images (product_id, image_type);
create index if not exists product_images_sort_order_idx
  on public.product_images (product_id, sort_order);
create index if not exists product_images_dam_asset_idx
  on public.product_images (dam_asset_id)
  where dam_asset_id is not null;

alter table public.product_images enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename  = 'product_images'
      and policyname = 'product_images_public_read'
  ) then
    create policy product_images_public_read
      on public.product_images for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename  = 'product_images'
      and policyname = 'product_images_service_write'
  ) then
    create policy product_images_service_write
      on public.product_images for all to service_role
      using (true) with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename  = 'product_images'
      and policyname = 'product_images_admin_write'
  ) then
    create policy product_images_admin_write
      on public.product_images for all to authenticated
      using (
        (auth.jwt() ->> 'role') = 'admin'
        or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
      )
      with check (
        (auth.jwt() ->> 'role') = 'admin'
        or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
      );
  end if;
end $$;

-- ============================================================
-- 4. PRODUCT VARIANTS — V2 column additions
--    The table may have been created by 20260718_inventory_v1.sql
--    with V1 column names. We ADD every V2 column that may be missing.
--    Every statement uses ADD COLUMN IF NOT EXISTS.
-- ============================================================

-- 4a. Ensure the table exists (guard for clean-DB scenario)
create table if not exists public.product_variants (
  id             bigint generated by default as identity primary key,
  product_id     bigint not null references public.products (id) on delete cascade,
  sku            text   not null,
  mrp            numeric(12,2) not null default 0 check (mrp >= 0),
  selling_price  numeric(12,2) not null default 0 check (selling_price >= 0),
  stock          integer not null default 0 check (stock >= 0),
  status         text    not null default 'active',
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- 4b. Add V2-specific columns (all idempotent)
do $$ begin

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'product_variants'
      and column_name = 'size_id'
  ) then
    alter table public.product_variants
      add column size_id bigint references public.size_master (id) on delete set null;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'product_variants'
      and column_name = 'size_label'
  ) then
    alter table public.product_variants add column size_label text;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'product_variants'
      and column_name = 'cost'
  ) then
    alter table public.product_variants
      add column cost numeric(12,2) check (cost >= 0);
  end if;

  -- V2 canonical stock column (V1 used stock_current)
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'product_variants'
      and column_name = 'stock'
  ) then
    alter table public.product_variants
      add column stock integer not null default 0 check (stock >= 0);
  end if;

  -- V2 canonical reserved column (V1 used stock_reserved)
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'product_variants'
      and column_name = 'reserved_stock'
  ) then
    alter table public.product_variants
      add column reserved_stock integer not null default 0 check (reserved_stock >= 0);
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'product_variants'
      and column_name = 'barcode'
  ) then
    alter table public.product_variants add column barcode text;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'product_variants'
      and column_name = 'mrp'
  ) then
    alter table public.product_variants
      add column mrp numeric(12,2) not null default 0 check (mrp >= 0);
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'product_variants'
      and column_name = 'selling_price'
  ) then
    alter table public.product_variants
      add column selling_price numeric(12,2) not null default 0 check (selling_price >= 0);
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'product_variants'
      and column_name = 'weight_grams'
  ) then
    alter table public.product_variants
      add column weight_grams integer check (weight_grams >= 0);
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'product_variants'
      and column_name = 'length_cm'
  ) then
    alter table public.product_variants
      add column length_cm numeric(8,2) check (length_cm >= 0);
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'product_variants'
      and column_name = 'width_cm'
  ) then
    alter table public.product_variants
      add column width_cm numeric(8,2) check (width_cm >= 0);
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'product_variants'
      and column_name = 'height_cm'
  ) then
    alter table public.product_variants
      add column height_cm numeric(8,2) check (height_cm >= 0);
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'product_variants'
      and column_name = 'is_default'
  ) then
    alter table public.product_variants
      add column is_default boolean not null default false;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'product_variants'
      and column_name = 'sort_order'
  ) then
    alter table public.product_variants
      add column sort_order integer not null default 0;
  end if;

  -- selling_lte_mrp constraint
  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema    = 'public'
      and table_name      = 'product_variants'
      and constraint_name = 'selling_lte_mrp'
  ) then
    alter table public.product_variants
      add constraint selling_lte_mrp check (selling_price <= mrp);
  end if;

end $$;

-- Unique SKU constraint (guard for V1 tables that used a unique index instead)
do $$ begin
  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema    = 'public'
      and table_name      = 'product_variants'
      and constraint_name = 'product_variants_sku_key'
      and constraint_type = 'UNIQUE'
  ) then
    -- only add if the unique index from V1 also doesn't cover it
    if not exists (
      select 1 from pg_indexes
      where schemaname = 'public'
        and tablename  = 'product_variants'
        and indexname  = 'idx_product_variants_sku'
    ) then
      alter table public.product_variants add constraint product_variants_sku_key unique (sku);
    end if;
  end if;
end $$;

-- updated_at trigger (DROP IF EXISTS makes idempotent)
drop trigger if exists product_variants_set_updated_at on public.product_variants;
create trigger product_variants_set_updated_at
  before update on public.product_variants
  for each row execute function public.set_updated_at();

create index if not exists product_variants_product_id_idx
  on public.product_variants (product_id);
create index if not exists product_variants_sku_idx
  on public.product_variants (sku);
create index if not exists product_variants_status_idx
  on public.product_variants (product_id, status);
create index if not exists product_variants_default_idx
  on public.product_variants (product_id, is_default);
create index if not exists product_variants_size_id_idx
  on public.product_variants (size_id)
  where size_id is not null;

alter table public.product_variants enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename  = 'product_variants'
      and policyname = 'product_variants_public_read'
  ) then
    create policy product_variants_public_read
      on public.product_variants for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename  = 'product_variants'
      and policyname = 'product_variants_service_write'
  ) then
    create policy product_variants_service_write
      on public.product_variants for all to service_role
      using (true) with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename  = 'product_variants'
      and policyname = 'product_variants_admin_write'
  ) then
    create policy product_variants_admin_write
      on public.product_variants for all to authenticated
      using (
        (auth.jwt() ->> 'role') = 'admin'
        or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
      )
      with check (
        (auth.jwt() ->> 'role') = 'admin'
        or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
      );
  end if;
end $$;

-- ============================================================
-- 5. PRODUCT TAGS (join table)
--    Depends on: public.products (initial schema)
--                public.tags     (Section 2 above — now exists)
-- ============================================================

create table if not exists public.product_tags (
  product_id bigint not null references public.products (id) on delete cascade,
  tag_id     bigint not null references public.tags     (id) on delete cascade,
  primary key (product_id, tag_id)
);

create index if not exists product_tags_product_id_idx on public.product_tags (product_id);
create index if not exists product_tags_tag_id_idx     on public.product_tags (tag_id);

alter table public.product_tags enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename  = 'product_tags'
      and policyname = 'product_tags_public_read'
  ) then
    create policy product_tags_public_read
      on public.product_tags for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename  = 'product_tags'
      and policyname = 'product_tags_service_write'
  ) then
    create policy product_tags_service_write
      on public.product_tags for all to service_role
      using (true) with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename  = 'product_tags'
      and policyname = 'product_tags_admin_write'
  ) then
    create policy product_tags_admin_write
      on public.product_tags for all to authenticated
      using (
        (auth.jwt() ->> 'role') = 'admin'
        or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
      )
      with check (
        (auth.jwt() ->> 'role') = 'admin'
        or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
      );
  end if;
end $$;

-- ============================================================
-- 6. PRODUCT AUDIT LOG
-- ============================================================

create table if not exists public.product_audit_log (
  id          bigint generated by default as identity primary key,
  product_id  bigint references public.products (id) on delete set null,
  actor_id    uuid   references auth.users (id)   on delete set null,
  event       text   not null,   -- created | updated | published | deactivated | deleted
  diff        jsonb,             -- {before:{}, after:{}} snapshot
  metadata    jsonb,
  created_at  timestamptz not null default now()
);

create index if not exists product_audit_log_product_id_idx
  on public.product_audit_log (product_id);
create index if not exists product_audit_log_created_at_idx
  on public.product_audit_log (created_at desc);
create index if not exists product_audit_log_actor_id_idx
  on public.product_audit_log (actor_id);
create index if not exists product_audit_log_event_idx
  on public.product_audit_log (event);

alter table public.product_audit_log enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename  = 'product_audit_log'
      and policyname = 'product_audit_log_service_write'
  ) then
    create policy product_audit_log_service_write
      on public.product_audit_log for all to service_role
      using (true) with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename  = 'product_audit_log'
      and policyname = 'product_audit_log_auth_read'
  ) then
    create policy product_audit_log_auth_read
      on public.product_audit_log for select to authenticated
      using (true);
  end if;
end $$;

-- ============================================================
-- 7. RELOAD POSTGREST SCHEMA CACHE
-- ============================================================

select pg_notify('pgrst', 'reload schema');
