-- ============================================================
-- PRODUCTION SCHEMA CATCHUP
-- 20260802235900_production_schema_catchup.sql
--
-- Covers every schema object not confirmed applied to production:
--   • Order Management V2 Foundation
--   • Inventory V1
--   • Fulfillment Inventory
--   • DAM (Sprint 13, three parts)
--   • Inventory Sprint 4 Domain
--   • Inventory Summary View
--   • product_variants compatibility columns
--
-- Safety guarantees:
--   * All CREATE TABLE        → IF NOT EXISTS
--   * All ALTER TABLE ADD COL → ADD COLUMN IF NOT EXISTS
--   * All CREATE INDEX        → IF NOT EXISTS
--   * All CREATE TYPE / enum  → DO $$ BEGIN ... EXCEPTION WHEN duplicate_object THEN NULL END $$
--   * All CREATE POLICY       → guarded by pg_policies existence check
--   * All CREATE OR REPLACE   → safe for functions/views
--   * No DROP TABLE / DROP COLUMN
--   * No data mutations
--   * Idempotent: safe to run more than once
-- ============================================================

-- ============================================================
-- SECTION 1 — SHARED HELPERS
-- ============================================================

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ============================================================
-- SECTION 2 — ORDER MANAGEMENT V2 FOUNDATION
-- ============================================================

-- 2a. Enums
do $$ begin
  create type public.order_status_v2 as enum (
    'draft','pending_payment','payment_failed','payment_processing',
    'confirmed','awaiting_fulfillment','partially_shipped','shipped',
    'out_for_delivery','delivered','return_requested','return_approved',
    'return_rejected','returned','refund_initiated','refunded',
    'partially_refunded','cancelled','on_hold'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.order_item_status_v2 as enum (
    'pending','confirmed','packed','shipped','delivered',
    'return_requested','returned','cancelled','refunded'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.fulfillment_status as enum (
    'unfulfilled','partial','fulfilled','returned'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.refund_reason as enum (
    'customer_request','defective','wrong_item','not_delivered','other'
  );
exception when duplicate_object then null; end $$;

-- 2b. orders_v2
create table if not exists public.orders_v2 (
  id                  bigint generated by default as identity primary key,
  order_number        text    not null unique,
  user_id             uuid    references auth.users (id) on delete set null,
  guest_email         text,
  status              public.order_status_v2 not null default 'draft',
  fulfillment_status  public.fulfillment_status not null default 'unfulfilled',

  -- pricing
  subtotal            numeric(14,2) not null default 0 check (subtotal >= 0),
  discount_amount     numeric(14,2) not null default 0 check (discount_amount >= 0),
  coupon_code         text,
  coupon_discount     numeric(14,2) not null default 0 check (coupon_discount >= 0),
  shipping_charge     numeric(14,2) not null default 0 check (shipping_charge >= 0),
  tax_amount          numeric(14,2) not null default 0 check (tax_amount >= 0),
  total               numeric(14,2) not null default 0 check (total >= 0),
  refunded_amount     numeric(14,2) not null default 0 check (refunded_amount >= 0),

  -- addresses (jsonb snapshot at order time)
  shipping_address    jsonb,
  billing_address     jsonb,

  -- payment
  payment_method      text,
  payment_gateway     text,
  payment_gateway_ref text,
  paid_at             timestamptz,

  -- shipping
  shipping_provider   text,
  tracking_number     text,
  tracking_url        text,
  shipped_at          timestamptz,
  delivered_at        timestamptz,
  estimated_delivery  date,

  -- meta
  notes               text,
  internal_notes      text,
  tags                text[],
  metadata            jsonb,
  ip_address          inet,
  user_agent          text,

  cancelled_at        timestamptz,
  cancelled_reason    text,
  cancelled_by        uuid references auth.users (id) on delete set null,

  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

drop trigger if exists orders_v2_set_updated_at on public.orders_v2;
create trigger orders_v2_set_updated_at
  before update on public.orders_v2
  for each row execute function public.set_updated_at();

create index if not exists orders_v2_order_number_idx      on public.orders_v2 (order_number);
create index if not exists orders_v2_user_id_idx           on public.orders_v2 (user_id);
create index if not exists orders_v2_status_idx            on public.orders_v2 (status);
create index if not exists orders_v2_created_at_idx        on public.orders_v2 (created_at desc);
create index if not exists orders_v2_fulfillment_status_idx on public.orders_v2 (fulfillment_status);

alter table public.orders_v2 enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='orders_v2' and policyname='orders_v2_owner_read') then
    create policy orders_v2_owner_read on public.orders_v2 for select to authenticated
      using (user_id = auth.uid());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='orders_v2' and policyname='orders_v2_service_all') then
    create policy orders_v2_service_all on public.orders_v2 for all to service_role
      using (true) with check (true);
  end if;
end $$;

-- 2c. order_items_v2
create table if not exists public.order_items_v2 (
  id              bigint generated by default as identity primary key,
  order_id        bigint not null references public.orders_v2 (id) on delete cascade,
  product_id      bigint references public.products (id) on delete set null,
  variant_id      bigint,  -- soft ref; set null if variant deleted
  sku             text    not null,
  product_name    text    not null,
  variant_label   text,
  image_url       text,
  quantity        integer not null check (quantity > 0),
  unit_mrp        numeric(12,2) not null check (unit_mrp >= 0),
  unit_price      numeric(12,2) not null check (unit_price >= 0),
  discount        numeric(12,2) not null default 0 check (discount >= 0),
  tax_rate        numeric(6,4) not null default 0,
  tax_amount      numeric(12,2) not null default 0,
  total           numeric(12,2) not null check (total >= 0),
  status          public.order_item_status_v2 not null default 'pending',
  fulfilled_qty   integer not null default 0,
  returned_qty    integer not null default 0,
  refunded_amount numeric(12,2) not null default 0,
  metadata        jsonb,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

drop trigger if exists order_items_v2_set_updated_at on public.order_items_v2;
create trigger order_items_v2_set_updated_at
  before update on public.order_items_v2
  for each row execute function public.set_updated_at();

create index if not exists order_items_v2_order_id_idx   on public.order_items_v2 (order_id);
create index if not exists order_items_v2_product_id_idx on public.order_items_v2 (product_id);
create index if not exists order_items_v2_sku_idx        on public.order_items_v2 (sku);

alter table public.order_items_v2 enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='order_items_v2' and policyname='order_items_v2_owner_read') then
    create policy order_items_v2_owner_read on public.order_items_v2 for select to authenticated
      using (exists (select 1 from public.orders_v2 o where o.id = order_id and o.user_id = auth.uid()));
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='order_items_v2' and policyname='order_items_v2_service_all') then
    create policy order_items_v2_service_all on public.order_items_v2 for all to service_role
      using (true) with check (true);
  end if;
end $$;

-- 2d. order_status_history
create table if not exists public.order_status_history (
  id         bigint generated by default as identity primary key,
  order_id   bigint not null references public.orders_v2 (id) on delete cascade,
  from_status public.order_status_v2,
  to_status   public.order_status_v2 not null,
  actor_id    uuid references auth.users (id) on delete set null,
  note        text,
  metadata    jsonb,
  created_at  timestamptz not null default now()
);

create index if not exists order_status_history_order_id_idx  on public.order_status_history (order_id);
create index if not exists order_status_history_created_at_idx on public.order_status_history (created_at desc);

alter table public.order_status_history enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='order_status_history' and policyname='order_status_history_service_all') then
    create policy order_status_history_service_all on public.order_status_history for all to service_role
      using (true) with check (true);
  end if;
end $$;

-- 2e. order_refunds
create table if not exists public.order_refunds (
  id              bigint generated by default as identity primary key,
  order_id        bigint not null references public.orders_v2 (id) on delete cascade,
  order_item_id   bigint references public.order_items_v2 (id) on delete set null,
  amount          numeric(12,2) not null check (amount > 0),
  reason          public.refund_reason not null default 'other',
  notes           text,
  gateway_ref     text,
  processed_by    uuid references auth.users (id) on delete set null,
  processed_at    timestamptz,
  created_at      timestamptz not null default now()
);

create index if not exists order_refunds_order_id_idx on public.order_refunds (order_id);

alter table public.order_refunds enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='order_refunds' and policyname='order_refunds_service_all') then
    create policy order_refunds_service_all on public.order_refunds for all to service_role
      using (true) with check (true);
  end if;
end $$;

-- ============================================================
-- SECTION 3 — INVENTORY V1
-- ============================================================

-- 3a. Enums
do $$ begin
  create type public.inventory_movement_type as enum (
    'purchase','sale','return','adjustment','transfer_in','transfer_out',
    'damage','expired','initial_stock','reservation','reservation_release'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.inventory_location_type as enum (
    'warehouse','store','transit','virtual'
  );
exception when duplicate_object then null; end $$;

-- 3b. inventory_locations
create table if not exists public.inventory_locations (
  id          bigint generated by default as identity primary key,
  name        text    not null unique,
  code        text    not null unique,
  type        public.inventory_location_type not null default 'warehouse',
  address     jsonb,
  active      boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

drop trigger if exists inventory_locations_set_updated_at on public.inventory_locations;
create trigger inventory_locations_set_updated_at
  before update on public.inventory_locations
  for each row execute function public.set_updated_at();

alter table public.inventory_locations enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='inventory_locations' and policyname='inventory_locations_service_all') then
    create policy inventory_locations_service_all on public.inventory_locations for all to service_role
      using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='inventory_locations' and policyname='inventory_locations_auth_read') then
    create policy inventory_locations_auth_read on public.inventory_locations for select to authenticated
      using (true);
  end if;
end $$;

-- 3c. inventory_stock
create table if not exists public.inventory_stock (
  id              bigint generated by default as identity primary key,
  variant_id      bigint not null,  -- soft ref to product_variants
  location_id     bigint not null references public.inventory_locations (id) on delete restrict,
  quantity        integer not null default 0 check (quantity >= 0),
  reserved        integer not null default 0 check (reserved >= 0),
  reorder_point   integer not null default 0,
  reorder_qty     integer not null default 0,
  updated_at      timestamptz not null default now(),
  unique (variant_id, location_id)
);

drop trigger if exists inventory_stock_set_updated_at on public.inventory_stock;
create trigger inventory_stock_set_updated_at
  before update on public.inventory_stock
  for each row execute function public.set_updated_at();

create index if not exists inventory_stock_variant_id_idx   on public.inventory_stock (variant_id);
create index if not exists inventory_stock_location_id_idx  on public.inventory_stock (location_id);

alter table public.inventory_stock enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='inventory_stock' and policyname='inventory_stock_service_all') then
    create policy inventory_stock_service_all on public.inventory_stock for all to service_role
      using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='inventory_stock' and policyname='inventory_stock_auth_read') then
    create policy inventory_stock_auth_read on public.inventory_stock for select to authenticated
      using (true);
  end if;
end $$;

-- 3d. inventory_movements
create table if not exists public.inventory_movements (
  id              bigint generated by default as identity primary key,
  variant_id      bigint not null,
  location_id     bigint references public.inventory_locations (id) on delete set null,
  movement_type   public.inventory_movement_type not null,
  quantity        integer not null,
  reference_type  text,     -- 'order','purchase_order','adjustment', etc.
  reference_id    text,
  note            text,
  actor_id        uuid references auth.users (id) on delete set null,
  created_at      timestamptz not null default now()
);

create index if not exists inventory_movements_variant_id_idx    on public.inventory_movements (variant_id);
create index if not exists inventory_movements_location_id_idx   on public.inventory_movements (location_id);
create index if not exists inventory_movements_created_at_idx    on public.inventory_movements (created_at desc);
create index if not exists inventory_movements_reference_idx     on public.inventory_movements (reference_type, reference_id);

alter table public.inventory_movements enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='inventory_movements' and policyname='inventory_movements_service_all') then
    create policy inventory_movements_service_all on public.inventory_movements for all to service_role
      using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='inventory_movements' and policyname='inventory_movements_auth_read') then
    create policy inventory_movements_auth_read on public.inventory_movements for select to authenticated
      using (true);
  end if;
end $$;

-- ============================================================
-- SECTION 4 — FULFILLMENT INVENTORY
-- ============================================================

-- 4a. Enums
do $$ begin
  create type public.shipment_status as enum (
    'pending','processing','packed','handed_to_carrier',
    'in_transit','out_for_delivery','delivered','failed_delivery',
    'returned_to_origin','cancelled'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.purchase_order_status as enum (
    'draft','submitted','confirmed','partial','received','cancelled'
  );
exception when duplicate_object then null; end $$;

-- 4b. shipments
create table if not exists public.shipments (
  id                  bigint generated by default as identity primary key,
  order_id            bigint references public.orders_v2 (id) on delete set null,
  order_number        text,
  status              public.shipment_status not null default 'pending',
  carrier             text,
  service_type        text,
  tracking_number     text,
  tracking_url        text,
  label_url           text,
  weight_grams        integer,
  dimensions          jsonb,
  shipping_address    jsonb,
  estimated_delivery  date,
  shipped_at          timestamptz,
  delivered_at        timestamptz,
  notes               text,
  metadata            jsonb,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

drop trigger if exists shipments_set_updated_at on public.shipments;
create trigger shipments_set_updated_at
  before update on public.shipments
  for each row execute function public.set_updated_at();

create index if not exists shipments_order_id_idx       on public.shipments (order_id);
create index if not exists shipments_tracking_number_idx on public.shipments (tracking_number);
create index if not exists shipments_status_idx         on public.shipments (status);

alter table public.shipments enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='shipments' and policyname='shipments_service_all') then
    create policy shipments_service_all on public.shipments for all to service_role
      using (true) with check (true);
  end if;
end $$;

-- 4c. shipment_items
create table if not exists public.shipment_items (
  id              bigint generated by default as identity primary key,
  shipment_id     bigint not null references public.shipments (id) on delete cascade,
  order_item_id   bigint references public.order_items_v2 (id) on delete set null,
  variant_id      bigint,
  sku             text    not null,
  quantity        integer not null check (quantity > 0),
  created_at      timestamptz not null default now()
);

create index if not exists shipment_items_shipment_id_idx   on public.shipment_items (shipment_id);
create index if not exists shipment_items_order_item_id_idx on public.shipment_items (order_item_id);

alter table public.shipment_items enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='shipment_items' and policyname='shipment_items_service_all') then
    create policy shipment_items_service_all on public.shipment_items for all to service_role
      using (true) with check (true);
  end if;
end $$;

-- 4d. purchase_orders
create table if not exists public.purchase_orders (
  id              bigint generated by default as identity primary key,
  po_number       text    not null unique,
  supplier_name   text,
  supplier_ref    text,
  location_id     bigint references public.inventory_locations (id) on delete set null,
  status          public.purchase_order_status not null default 'draft',
  expected_date   date,
  received_at     timestamptz,
  notes           text,
  total_cost      numeric(14,2),
  created_by      uuid references auth.users (id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

drop trigger if exists purchase_orders_set_updated_at on public.purchase_orders;
create trigger purchase_orders_set_updated_at
  before update on public.purchase_orders
  for each row execute function public.set_updated_at();

create index if not exists purchase_orders_po_number_idx on public.purchase_orders (po_number);
create index if not exists purchase_orders_status_idx    on public.purchase_orders (status);

alter table public.purchase_orders enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='purchase_orders' and policyname='purchase_orders_service_all') then
    create policy purchase_orders_service_all on public.purchase_orders for all to service_role
      using (true) with check (true);
  end if;
end $$;

-- 4e. purchase_order_items
create table if not exists public.purchase_order_items (
  id              bigint generated by default as identity primary key,
  po_id           bigint not null references public.purchase_orders (id) on delete cascade,
  variant_id      bigint,
  sku             text    not null,
  product_name    text,
  ordered_qty     integer not null check (ordered_qty > 0),
  received_qty    integer not null default 0 check (received_qty >= 0),
  unit_cost       numeric(12,2),
  created_at      timestamptz not null default now()
);

create index if not exists purchase_order_items_po_id_idx      on public.purchase_order_items (po_id);
create index if not exists purchase_order_items_variant_id_idx on public.purchase_order_items (variant_id);

alter table public.purchase_order_items enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='purchase_order_items' and policyname='purchase_order_items_service_all') then
    create policy purchase_order_items_service_all on public.purchase_order_items for all to service_role
      using (true) with check (true);
  end if;
end $$;

-- ============================================================
-- SECTION 5 — DAM (Digital Asset Management)
-- ============================================================

-- 5a. Enums
do $$ begin
  create type public.dam_asset_type as enum (
    'image','video','document','audio','other'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.dam_asset_status as enum (
    'uploading','processing','ready','failed','archived'
  );
exception when duplicate_object then null; end $$;

-- 5b. dam_folders
create table if not exists public.dam_folders (
  id          bigint generated by default as identity primary key,
  parent_id   bigint references public.dam_folders (id) on delete cascade,
  name        text    not null,
  slug        text    not null,
  path        text    not null,  -- materialized path e.g. /products/sarees/
  created_by  uuid references auth.users (id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (parent_id, slug)
);

drop trigger if exists dam_folders_set_updated_at on public.dam_folders;
create trigger dam_folders_set_updated_at
  before update on public.dam_folders
  for each row execute function public.set_updated_at();

create index if not exists dam_folders_parent_id_idx on public.dam_folders (parent_id);
create index if not exists dam_folders_path_idx      on public.dam_folders (path);

alter table public.dam_folders enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='dam_folders' and policyname='dam_folders_service_all') then
    create policy dam_folders_service_all on public.dam_folders for all to service_role
      using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='dam_folders' and policyname='dam_folders_auth_read') then
    create policy dam_folders_auth_read on public.dam_folders for select to authenticated
      using (true);
  end if;
end $$;

-- 5c. dam_assets
create table if not exists public.dam_assets (
  id              bigint generated by default as identity primary key,
  folder_id       bigint references public.dam_folders (id) on delete set null,
  asset_type      public.dam_asset_type not null default 'image',
  status          public.dam_asset_status not null default 'uploading',
  original_name   text    not null,
  storage_path    text    not null unique,
  public_url      text,
  cdn_url         text,
  mime_type       text,
  size_bytes      bigint,
  width           integer,
  height          integer,
  duration_sec    numeric(10,3),
  alt_text        text,
  title           text,
  description     text,
  tags            text[],
  metadata        jsonb,
  hash_md5        text,
  uploaded_by     uuid references auth.users (id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

drop trigger if exists dam_assets_set_updated_at on public.dam_assets;
create trigger dam_assets_set_updated_at
  before update on public.dam_assets
  for each row execute function public.set_updated_at();

create index if not exists dam_assets_folder_id_idx    on public.dam_assets (folder_id);
create index if not exists dam_assets_asset_type_idx   on public.dam_assets (asset_type);
create index if not exists dam_assets_status_idx       on public.dam_assets (status);
create index if not exists dam_assets_storage_path_idx on public.dam_assets (storage_path);
create index if not exists dam_assets_uploaded_by_idx  on public.dam_assets (uploaded_by);
create index if not exists dam_assets_created_at_idx   on public.dam_assets (created_at desc);
create index if not exists dam_assets_tags_idx         on public.dam_assets using gin (tags);

alter table public.dam_assets enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='dam_assets' and policyname='dam_assets_service_all') then
    create policy dam_assets_service_all on public.dam_assets for all to service_role
      using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='dam_assets' and policyname='dam_assets_auth_read') then
    create policy dam_assets_auth_read on public.dam_assets for select to authenticated
      using (true);
  end if;
end $$;

-- 5d. dam_asset_usage  (links assets to any entity)
create table if not exists public.dam_asset_usage (
  id              bigint generated by default as identity primary key,
  asset_id        bigint not null references public.dam_assets (id) on delete cascade,
  entity_type     text    not null,   -- 'product','variant','category', etc.
  entity_id       text    not null,
  usage_context   text,               -- 'primary_image','gallery','banner', etc.
  sort_order      integer not null default 0,
  created_at      timestamptz not null default now(),
  unique (asset_id, entity_type, entity_id, usage_context)
);

create index if not exists dam_asset_usage_asset_id_idx    on public.dam_asset_usage (asset_id);
create index if not exists dam_asset_usage_entity_idx      on public.dam_asset_usage (entity_type, entity_id);

alter table public.dam_asset_usage enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='dam_asset_usage' and policyname='dam_asset_usage_service_all') then
    create policy dam_asset_usage_service_all on public.dam_asset_usage for all to service_role
      using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='dam_asset_usage' and policyname='dam_asset_usage_auth_read') then
    create policy dam_asset_usage_auth_read on public.dam_asset_usage for select to authenticated
      using (true);
  end if;
end $$;

-- 5e. dam_processing_jobs
create table if not exists public.dam_processing_jobs (
  id              bigint generated by default as identity primary key,
  asset_id        bigint not null references public.dam_assets (id) on delete cascade,
  job_type        text    not null,  -- 'thumbnail','webp_convert','video_transcode', etc.
  status          text    not null default 'queued',
  attempts        integer not null default 0,
  last_error      text,
  result          jsonb,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

drop trigger if exists dam_processing_jobs_set_updated_at on public.dam_processing_jobs;
create trigger dam_processing_jobs_set_updated_at
  before update on public.dam_processing_jobs
  for each row execute function public.set_updated_at();

create index if not exists dam_processing_jobs_asset_id_idx on public.dam_processing_jobs (asset_id);
create index if not exists dam_processing_jobs_status_idx   on public.dam_processing_jobs (status);

alter table public.dam_processing_jobs enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='dam_processing_jobs' and policyname='dam_processing_jobs_service_all') then
    create policy dam_processing_jobs_service_all on public.dam_processing_jobs for all to service_role
      using (true) with check (true);
  end if;
end $$;

-- ============================================================
-- SECTION 6 — INVENTORY SPRINT 4 DOMAIN
-- ============================================================

-- 6a. Enums
do $$ begin
  create type public.stock_alert_type as enum (
    'low_stock','out_of_stock','reorder_point','overstock'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.inventory_adjustment_reason as enum (
    'count_correction','damage','theft','expiry','found','transfer','other'
  );
exception when duplicate_object then null; end $$;

-- 6b. stock_alerts
create table if not exists public.stock_alerts (
  id              bigint generated by default as identity primary key,
  variant_id      bigint not null,
  location_id     bigint references public.inventory_locations (id) on delete set null,
  alert_type      public.stock_alert_type not null,
  threshold       integer,
  current_stock   integer,
  acknowledged    boolean not null default false,
  acknowledged_by uuid references auth.users (id) on delete set null,
  acknowledged_at timestamptz,
  created_at      timestamptz not null default now()
);

create index if not exists stock_alerts_variant_id_idx      on public.stock_alerts (variant_id);
create index if not exists stock_alerts_acknowledged_idx    on public.stock_alerts (acknowledged);
create index if not exists stock_alerts_created_at_idx      on public.stock_alerts (created_at desc);

alter table public.stock_alerts enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='stock_alerts' and policyname='stock_alerts_service_all') then
    create policy stock_alerts_service_all on public.stock_alerts for all to service_role
      using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='stock_alerts' and policyname='stock_alerts_auth_read') then
    create policy stock_alerts_auth_read on public.stock_alerts for select to authenticated
      using (true);
  end if;
end $$;

-- 6c. inventory_adjustments
create table if not exists public.inventory_adjustments (
  id              bigint generated by default as identity primary key,
  variant_id      bigint not null,
  location_id     bigint references public.inventory_locations (id) on delete set null,
  quantity_before integer not null,
  quantity_after  integer not null,
  delta           integer not null,
  reason          public.inventory_adjustment_reason not null default 'other',
  note            text,
  reference_doc   text,
  approved_by     uuid references auth.users (id) on delete set null,
  created_by      uuid references auth.users (id) on delete set null,
  created_at      timestamptz not null default now()
);

create index if not exists inventory_adjustments_variant_id_idx   on public.inventory_adjustments (variant_id);
create index if not exists inventory_adjustments_location_id_idx  on public.inventory_adjustments (location_id);
create index if not exists inventory_adjustments_created_at_idx   on public.inventory_adjustments (created_at desc);

alter table public.inventory_adjustments enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='inventory_adjustments' and policyname='inventory_adjustments_service_all') then
    create policy inventory_adjustments_service_all on public.inventory_adjustments for all to service_role
      using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='inventory_adjustments' and policyname='inventory_adjustments_auth_read') then
    create policy inventory_adjustments_auth_read on public.inventory_adjustments for select to authenticated
      using (true);
  end if;
end $$;

-- 6d. inventory_reservations
create table if not exists public.inventory_reservations (
  id              bigint generated by default as identity primary key,
  variant_id      bigint not null,
  location_id     bigint references public.inventory_locations (id) on delete set null,
  order_id        bigint references public.orders_v2 (id) on delete cascade,
  quantity        integer not null check (quantity > 0),
  expires_at      timestamptz,
  released_at     timestamptz,
  created_at      timestamptz not null default now()
);

create index if not exists inventory_reservations_variant_id_idx  on public.inventory_reservations (variant_id);
create index if not exists inventory_reservations_order_id_idx    on public.inventory_reservations (order_id);
create index if not exists inventory_reservations_expires_at_idx  on public.inventory_reservations (expires_at);

alter table public.inventory_reservations enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='inventory_reservations' and policyname='inventory_reservations_service_all') then
    create policy inventory_reservations_service_all on public.inventory_reservations for all to service_role
      using (true) with check (true);
  end if;
end $$;

-- ============================================================
-- SECTION 7 — INVENTORY SUMMARY VIEW
-- ============================================================

create or replace view public.inventory_summary as
select
  s.variant_id,
  l.id                                     as location_id,
  l.name                                   as location_name,
  l.code                                   as location_code,
  s.quantity,
  s.reserved,
  greatest(s.quantity - s.reserved, 0)    as available,
  s.reorder_point,
  s.reorder_qty,
  case
    when s.quantity = 0                          then 'out_of_stock'
    when s.quantity <= s.reorder_point           then 'low_stock'
    else 'in_stock'
  end                                      as stock_status,
  s.updated_at
from public.inventory_stock s
join public.inventory_locations l on l.id = s.location_id;

-- ============================================================
-- SECTION 8 — product_variants COMPATIBILITY COLUMNS
-- (safe additions; column already exists → no-op)
-- ============================================================

alter table public.product_variants
  add column if not exists color_id       bigint references public.attr_color   (id) on delete set null,
  add column if not exists fabric_id      bigint references public.attr_fabric  (id) on delete set null,
  add column if not exists images         jsonb    not null default '[]'::jsonb,
  add column if not exists attributes     jsonb    not null default '{}'::jsonb,
  add column if not exists deleted_at     timestamptz,
  add column if not exists deleted_by     uuid references auth.users (id) on delete set null;

create index if not exists product_variants_color_id_idx  on public.product_variants (color_id);
create index if not exists product_variants_fabric_id_idx on public.product_variants (fabric_id);
create index if not exists product_variants_deleted_at_idx on public.product_variants (deleted_at)
  where deleted_at is null;

-- ============================================================
-- SECTION 9 — SCHEMA CACHE RELOAD HINT
-- ============================================================
-- After applying this migration run:
--   SELECT pg_notify('pgrst', 'reload schema');
-- or reload via Dashboard → Settings → API → Reload schema
-- ============================================================
