create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text not null unique,
  slug text not null unique,
  category text not null,
  collection text not null,
  brand text not null default 'Bansari Collections',
  fabric text not null,
  color text not null,
  sizes text[] not null default '{}',
  price numeric(12, 2) not null default 0,
  compare_price numeric(12, 2),
  cost numeric(12, 2),
  stock integer not null default 0,
  hsn text not null,
  gst numeric(5, 2) not null default 5,
  description text not null,
  seo_title text not null,
  seo_description text not null,
  featured boolean not null default false,
  new_arrival boolean not null default false,
  best_seller boolean not null default false,
  active boolean not null default true,
  images jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_category_idx on public.products (category);
create index if not exists products_active_idx on public.products (active);
create index if not exists products_stock_idx on public.products (stock);
create index if not exists products_created_at_idx on public.products (created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;

create trigger products_set_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

alter table public.products enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'products'
      and policyname = 'Products are publicly readable'
  ) then
    create policy "Products are publicly readable"
      on public.products
      for select
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'products'
      and policyname = 'Authenticated users can manage products'
  ) then
    create policy "Authenticated users can manage products"
      on public.products
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'product-images',
  'product-images',
  true,
  10485760,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Product images are publicly readable'
  ) then
    create policy "Product images are publicly readable"
      on storage.objects
      for select
      using (bucket_id = 'product-images');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Authenticated users can upload product images'
  ) then
    create policy "Authenticated users can upload product images"
      on storage.objects
      for insert
      to authenticated
      with check (bucket_id = 'product-images');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Authenticated users can update product images'
  ) then
    create policy "Authenticated users can update product images"
      on storage.objects
      for update
      to authenticated
      using (bucket_id = 'product-images')
      with check (bucket_id = 'product-images');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Authenticated users can delete product images'
  ) then
    create policy "Authenticated users can delete product images"
      on storage.objects
      for delete
      to authenticated
      using (bucket_id = 'product-images');
  end if;
end $$;
