-- =============================================================
-- homepage_campaigns seed — 3 production editorial campaigns
-- Run once against your Supabase project:
--   psql $DATABASE_URL -f supabase/seeds/homepage_campaigns.sql
-- Or paste into the Supabase SQL editor.
-- All image paths reference Supabase Storage bucket: homepage
-- Replace image URLs with your actual uploaded asset URLs.
-- =============================================================

INSERT INTO public.homepage_campaigns (
  title,
  headline_line1,
  headline_highlight,
  headline_line2,
  description,
  cta_primary_text,
  cta_primary_link,
  cta_secondary_text,
  cta_secondary_link,
  desktop_image,
  tablet_image,
  mobile_image,
  video_url,
  image_alt,
  overlay_color,
  overlay_opacity,
  text_alignment,
  image_position,
  button_style,
  sort_order,
  priority,
  status,
  start_date,
  end_date
) VALUES
(
  'Wedding Edit 2025',
  'The Wedding Edit',
  '2025',
  '',
  'Bridal lehengas, embroidered sarees and ceremonial kurta sets — crafted for every ritual, every celebration, every memory.',
  'Shop Bridal',
  '/shop?occasion=wedding',
  'Explore Collections',
  '/collections',
  '/images/campaigns/wedding-2025-desktop.jpg',
  '/images/campaigns/wedding-2025-tablet.jpg',
  '/images/campaigns/wedding-2025-mobile.jpg',
  '',
  'Bansari Collections — bridal lehenga in ivory and gold zari, wedding editorial',
  '#0f0007',
  0.10,
  'left',
  'center',
  'filled',
  1,
  1,
  'published',
  NULL,
  NULL
),
(
  'Festive Sarees',
  'Sarees For',
  'Every Celebration',
  '',
  'From Banarasi silk to lightweight georgette — discover our curated edit of festive sarees for every occasion on the calendar.',
  'Shop Sarees',
  '/shop?category=sarees',
  'View All',
  '/shop',
  '/images/campaigns/sarees-desktop.jpg',
  '/images/campaigns/sarees-tablet.jpg',
  '/images/campaigns/sarees-mobile.jpg',
  '',
  'Bansari Collections — crimson Banarasi silk saree with gold zari border, festive editorial',
  '#0a0510',
  0.08,
  'left',
  'center',
  'filled',
  2,
  0,
  'published',
  NULL,
  NULL
),
(
  'New Arrivals',
  'Just Arrived',
  '',
  'Fresh Silhouettes',
  'Contemporary kurta sets, co-ord sets and anarkali styles — the newest additions to the Bansari edit, curated for the season.',
  'Explore New Arrivals',
  '/shop?filter=new',
  'All Categories',
  '/shop',
  '/images/campaigns/new-arrivals-desktop.jpg',
  '/images/campaigns/new-arrivals-tablet.jpg',
  '/images/campaigns/new-arrivals-mobile.jpg',
  '',
  'Bansari Collections — model in sage green embroidered kurta set, new arrivals editorial',
  '#080d0a',
  0.07,
  'left',
  'center',
  'ghost',
  3,
  0,
  'published',
  NULL,
  NULL
)
ON CONFLICT DO NOTHING;
