-- =============================================================================
-- BATCH 1 · Migration 14 (REVISED) — checkout_events
-- =============================================================================
-- REVISION CHANGELOG (2026-08-05)
--   P2: Added razorpay_order_id as first-class column (not buried in metadata).
--   P2: Added checkout_stage for funnel drop-off analysis.
--   P2: Added request_id for distributed tracing.
--   P2: Added order_id to link payment_success / order_created events.
--   P2: Added ip_hash and device_type for fraud detection.
--   P2: Added event_type CHECK constraint — typos now fail at INSERT time.
--   Fix: Widened cart_value to NUMERIC(14,2) to match orders.grand_total.
--   Fix: Added index on session_id for guest checkout funnel queries.
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.checkout_events (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Funnel event type — constrained to prevent typo writes
  -- CouponService, CheckoutService, WebhookDispatcher write to this table.
  event_type          TEXT        NOT NULL,

  -- Session identity
  customer_id         UUID,
  session_id          TEXT,

  -- Distributed trace ID: links this event to the API request that caused it.
  -- Set from the X-Request-ID header or generated by the service layer.
  -- Essential for debugging: correlate a payment_failed event to the exact
  -- API request, Razorpay call, and server log line.
  request_id          TEXT,

  -- Razorpay linkage: first-class column for payment-stage events.
  -- Not buried in metadata — directly queryable and indexable.
  razorpay_order_id   TEXT,

  -- Final order reference: populated for order_created / payment_success events.
  order_id            UUID,

  -- Funnel position at the time of the event.
  -- Enables drop-off analysis: what % of users who started checkout
  -- completed each stage?
  checkout_stage      TEXT
    CHECK (checkout_stage IN ('cart', 'address', 'payment', 'confirmation', 'completed')),

  -- Coupon fields (populated for coupon_* events)
  coupon_code         TEXT,
  reason              TEXT,

  -- Cart value at time of event (NUMERIC(14,2) matches orders.grand_total precision)
  cart_value          NUMERIC(14, 2),
  currency            TEXT        NOT NULL DEFAULT 'INR',

  -- Privacy-safe client fingerprint for fraud detection.
  -- SHA-256 hash of IP address — never raw IP (GDPR compliance).
  ip_hash             TEXT,
  -- 'mobile' | 'desktop' | 'tablet' — derived from User-Agent in service layer
  device_type         TEXT
    CHECK (device_type IN ('mobile', 'desktop', 'tablet', 'unknown')),

  -- Flexible structured payload for event-specific additional data.
  -- Examples:
  --   inventory_failed: {"product_id": 42, "requested": 3, "available": 1}
  --   payment_success:  {"payment_id": "pay_xxx", "method": "upi"}
  --   coupon_invalid:   {"attempted_code": "SAVE50"}
  metadata            JSONB,

  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- event_type CONSTRAINT
-- =============================================================================
-- Enforces canonical event type vocabulary. A typo in the service layer
-- (e.g., 'payment_succss') will now FAIL at INSERT time rather than
-- silently polluting analytics data.
--
-- To add a new event type: ALTER TABLE checkout_events DROP CONSTRAINT
-- checkout_events_event_type_check; then re-add with the new value.
-- This is a deliberate friction point — new event types require intentional
-- schema change, preventing ad-hoc string proliferation.
ALTER TABLE public.checkout_events
  ADD CONSTRAINT checkout_events_event_type_check
  CHECK (event_type IN (
    'checkout_started',
    'coupon_applied',
    'coupon_invalid',
    'coupon_expired',
    'coupon_inactive',
    'coupon_min_order',
    'coupon_usage_limit',
    'inventory_reserved',
    'inventory_failed',
    'reservation_released',
    'reservation_expired',
    'payment_initiated',
    'payment_success',
    'payment_failed',
    'order_created',
    'order_cancelled'
  ));

-- =============================================================================
-- INDEXES
-- =============================================================================

-- Analytics: events by type + time (e.g., daily coupon_invalid count)
CREATE INDEX IF NOT EXISTS checkout_events_type_idx
  ON public.checkout_events (event_type, created_at DESC);

-- Analytics: full funnel for a specific customer
CREATE INDEX IF NOT EXISTS checkout_events_customer_idx
  ON public.checkout_events (customer_id, created_at DESC)
  WHERE customer_id IS NOT NULL;

-- Guest checkout funnel (previously missing — would have caused full table scan)
CREATE INDEX IF NOT EXISTS checkout_events_session_idx
  ON public.checkout_events (session_id, created_at DESC)
  WHERE session_id IS NOT NULL;

-- Coupon performance dashboard
CREATE INDEX IF NOT EXISTS checkout_events_coupon_idx
  ON public.checkout_events (coupon_code, event_type)
  WHERE coupon_code IS NOT NULL;

-- Razorpay order event lookup (payment lifecycle tracing)
CREATE INDEX IF NOT EXISTS checkout_events_razorpay_idx
  ON public.checkout_events (razorpay_order_id)
  WHERE razorpay_order_id IS NOT NULL;

-- Distributed trace: find all events for a request_id during incident response
CREATE INDEX IF NOT EXISTS checkout_events_request_id_idx
  ON public.checkout_events (request_id)
  WHERE request_id IS NOT NULL;

-- Time-series pruning (pg_cron DELETE WHERE created_at < NOW() - INTERVAL '90 days')
CREATE INDEX IF NOT EXISTS checkout_events_created_at_idx
  ON public.checkout_events (created_at);

-- ── Security ─────────────────────────────────────────────────────────────────
ALTER TABLE public.checkout_events DISABLE ROW LEVEL SECURITY;

COMMIT;
